import { ApiCategory } from "./types";

export const apiCategories: ApiCategory[] = [
  {
    id: "webhooks",
    name: "Webhooks de Entrada",
    description: "Endpoints para enviar leads ao sistema a partir de fontes externas (Meta Ads, Google Ads, Landing Pages, n8n, Zapier, etc.)",
    icon: "webhook",
    endpoints: [
      {
        id: "lead-webhook",
        name: "Lead Webhook",
        description: "Endpoint principal e mais flexível para receber leads de qualquer fonte externa. Suporta campos personalizados, tags, colocação em pipes (funis) e campanhas, e disparo automático de agentes outbound.",
        category: "webhooks",
        version: "v1",
        method: "POST",
        path: "/functions/v1/lead-webhook",
        auth: {
          type: "api-key",
          header: "X-Webhook-Key",
          description: "Chave de API fornecida pelo administrador do sistema. Envie no header X-Webhook-Key.",
        },
        parameters: [
          {
            name: "source",
            type: "string",
            required: true,
            description: "Identificação da fonte do lead. Valores comuns: \"meta_ads\", \"google_ads\", \"landing_page\", \"site\", \"whatsapp\", \"remarketing\", \"cal\".",
          },
          {
            name: "fields",
            type: "object",
            required: true,
            description: "Dados do lead. Deve conter pelo menos phone ou email.",
            children: [
              { name: "name", type: "string", required: false, description: "Nome do lead." },
              { name: "phone", type: "string", required: false, description: "Telefone do lead (formato livre, ex: \"+5511999999999\")." },
              { name: "email", type: "string", required: false, description: "Email do lead." },
              { name: "company", type: "string", required: false, description: "Empresa do lead." },
              { name: "segment", type: "string", required: false, description: "Segmento de mercado." },
              { name: "faturamento", type: "string", required: false, description: "Faixa de faturamento." },
              { name: "urgency", type: "string", required: false, description: "Nível de urgência." },
              { name: "notes", type: "string", required: false, description: "Observações sobre o lead." },
              { name: "rating", type: "string", required: false, description: "Nota de 0 a 10." },
              { name: "[campo_personalizado]", type: "string", required: false, description: "Qualquer campo adicional será salvo como campo personalizado. Se o campo não existir na organização, será criado automaticamente." },
            ],
          },
          {
            name: "tags",
            type: "string[]",
            required: false,
            description: "Lista de tags para categorizar o lead. Tags inexistentes serão criadas automaticamente.",
          },
          {
            name: "campaign_id",
            type: "string",
            required: false,
            description: "ID da campanha de origem (para rastreamento).",
          },
          {
            name: "campaign_name",
            type: "string",
            required: false,
            description: "Nome da campanha (salvo como utm_campaign).",
          },
          {
            name: "organization_id",
            type: "string",
            required: false,
            description: "UUID da organização. Se não fornecido, usa a organização padrão.",
          },
          {
            name: "update_existing_if_match",
            type: "boolean",
            required: false,
            description: "Se true, busca por telefone/email e atualiza o lead existente ao invés de criar duplicata. Padrão: false (sempre cria novo lead).",
            defaultValue: "false",
          },
          {
            name: "place_in_pipe",
            type: "object",
            required: false,
            description: "Colocar o lead diretamente em um funil (pipe) específico.",
            children: [
              { name: "pipe", type: "string", required: true, description: "Nome do funil. Valores: \"whatsapp\", \"confirmacao\", \"propostas\"." },
              { name: "stage", type: "string", required: true, description: "Etapa do funil. Ex: \"novo\", \"abordado\", \"reuniao_marcada\"." },
              { name: "meeting_date", type: "string", required: false, description: "Data da reunião (ISO 8601). Salva também no lead como compromisso_date." },
            ],
          },
          {
            name: "place_in_campaign",
            type: "object",
            required: false,
            description: "Colocar o lead diretamente em uma campanha específica.",
            children: [
              { name: "campaign_id", type: "string", required: true, description: "UUID da campanha." },
              { name: "stage_id", type: "string", required: true, description: "UUID da etapa da campanha." },
              { name: "notes", type: "string", required: false, description: "Observações do lead nesta campanha." },
            ],
          },
          {
            name: "assigned_user_id",
            type: "string",
            required: false,
            description: "UUID do membro da equipe para atribuição direta como responsável (responsible_id), SDR e Closer. Se não fornecido, usa round-robin automático.",
          },
        ],
        requestExample: {
          source: "meta_ads",
          tags: ["facebook-campanha-jan", "lead-quente"],
          campaign_name: "Campanha Janeiro 2026",
          fields: {
            name: "João Silva",
            phone: "+5511999999999",
            email: "joao@empresa.com",
            company: "Empresa LTDA",
            segment: "tecnologia",
            faturamento: "1M-5M",
            cargo: "Diretor Comercial",
          },
          place_in_pipe: {
            pipe: "whatsapp",
            stage: "novo",
          },
          update_existing_if_match: true,
        },
        responseExample: {
          success: true,
          lead_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          is_new: true,
          message: "Lead criado com sucesso",
          custom_fields: {
            cargo: "saved",
          },
          place_in_pipe: {
            pipe: "whatsapp",
            stage: "novo",
          },
        },
        responseFields: [
          { name: "success", type: "boolean", required: true, description: "Indica se a operação foi bem-sucedida." },
          { name: "lead_id", type: "string", required: true, description: "UUID do lead criado ou atualizado." },
          { name: "is_new", type: "boolean", required: true, description: "true se um novo lead foi criado, false se um existente foi atualizado." },
          { name: "message", type: "string", required: true, description: "Mensagem descritiva do resultado." },
          { name: "custom_fields", type: "object", required: false, description: "Status de cada campo personalizado processado." },
          { name: "place_in_pipe", type: "object", required: false, description: "Confirmação do posicionamento no pipe (se solicitado)." },
          { name: "place_in_campaign", type: "object", required: false, description: "Confirmação do posicionamento na campanha (se solicitado)." },
          { name: "placed_in_campaign", type: "boolean", required: false, description: "true se o lead foi colocado na campanha com sucesso." },
        ],
        notes: [
          "O campo fields deve conter pelo menos phone ou email — caso contrário retorna erro 400.",
          "Campos em fields que não são padrão (name, phone, email, company, segment, faturamento, urgency, notes, rating) são automaticamente salvos como campos personalizados.",
          "Se update_existing_if_match=true, a busca por duplicata é feita por telefone e depois por email.",
          "Quando um novo lead é criado, o sistema verifica automaticamente se existe um agente Copilot outbound configurado e dispara a primeira mensagem.",
          "A distribuição automática (round-robin) de SDR/Closer acontece quando o lead é colocado em um pipe sem assigned_user_id. O responsible_id do lead é atualizado automaticamente.",
          "Origens reconhecidas: meta_ads, facebook, instagram, google_ads, landing_page, site, remarketing, whatsapp, calendly, cal. Outras origens são mapeadas como \"outro\".",
        ],
      },
      {
        id: "webhook-orchestrator",
        name: "Webhook Orchestrator",
        description: "Endpoint multi-ação para operações avançadas no CRM. Permite criar leads, agendar reuniões, atualizar dados, e transferir para atendimento humano — tudo em um único endpoint com diferentes actions.",
        category: "webhooks",
        version: "v1",
        method: "POST",
        path: "/functions/v1/webhook-orchestrator",
        auth: {
          type: "api-key",
          header: "X-API-Key ou campo api_key no body",
          description: "Chave de API. Pode ser enviada no header X-API-Key ou no campo api_key do body JSON.",
        },
        parameters: [
          {
            name: "action",
            type: "string",
            required: true,
            description: "Ação a ser executada. Valores: \"process_lead\", \"SCHEDULE_MEETING\", \"CREATE_LEAD\", \"UPDATE_LEAD\", \"TRANSFER_HUMAN\", \"UPDATE_CRM\".",
          },
          {
            name: "api_key",
            type: "string",
            required: true,
            description: "Chave de API (alternativa ao header X-API-Key).",
          },
          {
            name: "tenant_id",
            type: "string",
            required: false,
            description: "UUID da organização. Necessário para a maioria das ações.",
          },
          {
            name: "data",
            type: "object",
            required: true,
            description: "Dados específicos da ação. A estrutura varia conforme a action escolhida (veja exemplos abaixo).",
          },
        ],
        requestExample: {
          action: "process_lead",
          api_key: "sua-api-key",
          tenant_id: "uuid-da-organizacao",
          data: {
            name: "Maria Santos",
            email: "maria@empresa.com",
            phone: "+5521988887777",
            company: "Tech Corp",
            origin: "meta_ads",
            segment: "SaaS",
            notes: "Interessada no plano enterprise",
          },
        },
        responseExample: {
          success: true,
          message: "Lead criado com sucesso",
          lead_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          pipe: "whatsapp",
        },
        responseFields: [
          { name: "success", type: "boolean", required: true, description: "Indica se a operação foi bem-sucedida." },
          { name: "message", type: "string", required: true, description: "Mensagem descritiva do resultado." },
          { name: "lead_id", type: "string", required: false, description: "UUID do lead (para ações de lead)." },
          { name: "pipe", type: "string", required: false, description: "Funil onde o lead foi colocado." },
          { name: "deduplication_method", type: "string", required: false, description: "Método de deduplicação usado (se lead existente foi encontrado)." },
          { name: "meeting_date", type: "string", required: false, description: "Data da reunião agendada (para SCHEDULE_MEETING)." },
          { name: "error", type: "string", required: false, description: "Mensagem de erro (quando success=false)." },
        ],
        notes: [
          "A action \"process_lead\" tem deduplicação automática: busca por email e depois por nome+mesmo dia.",
          "A action \"SCHEDULE_MEETING\" requer lead_id e preferred_date no objeto data.",
          "A action \"UPDATE_LEAD\" aceita campos padrão (company, segment, urgency, faturamento, rating), campos personalizados (se existirem na org), e campos desconhecidos são salvos nas notas.",
          "A action \"TRANSFER_HUMAN\" desativa a IA no lead e muda o estado da conversa para WAITING_HUMAN.",
          "A action \"UPDATE_CRM\" é um placeholder — deve ser executada via n8n.",
          "A validação de subscription é feita quando tenant_id é fornecido. Organizações com subscription inativa/expirada são rejeitadas.",
        ],
      },
      {
        id: "webhook-new-lead",
        name: "Webhook New Lead",
        description: "Endpoint legado para criação de leads com deduplicação automática por telefone, email, ou nome+mesmo dia. Usado principalmente por fluxos n8n existentes.",
        category: "webhooks",
        version: "v1",
        method: "POST",
        path: "/functions/v1/webhook-new-lead",
        deprecated: true,
        deprecation_notice: "Use lead-webhook em vez deste endpoint. Será removido em 2027-01-01.",
        sunset_date: "2027-01-01",
        auth: {
          type: "api-key",
          header: "X-Webhook-Key",
          description: "API key da organização (obrigatória a partir de 2026-07-09)",
        },
        parameters: [
          { name: "name", type: "string", required: false, description: "Nome do lead." },
          { name: "email", type: "string", required: false, description: "Email do lead (usado para deduplicação)." },
          { name: "phone", type: "string", required: false, description: "Telefone do lead (usado para deduplicação, prioridade máxima)." },
          { name: "company", type: "string", required: false, description: "Empresa do lead." },
          { name: "origin", type: "string", required: false, description: "Origem do lead. Valores válidos: \"whatsapp\", \"meta_ads\", \"outro\", \"site\", \"remarketing\", \"google_ads\", \"cal\".", defaultValue: "outro" },
          { name: "segment", type: "string", required: false, description: "Segmento de mercado." },
          { name: "faturamento", type: "string", required: false, description: "Faixa de faturamento." },
          { name: "urgency", type: "string", required: false, description: "Nível de urgência." },
          { name: "notes", type: "string", required: false, description: "Observações." },
          { name: "rating", type: "number", required: false, description: "Nota de 0 a 10." },
          { name: "sdr_id", type: "string", required: false, description: "UUID do SDR responsável. Também define responsible_id no lead." },
          { name: "meeting_date", type: "string", required: false, description: "Data da reunião (ISO 8601)." },
          { name: "compromisso_date", type: "string", required: false, description: "Data do compromisso (ISO 8601). Se preenchido, o lead é roteado para o pipe de confirmação." },
          { name: "utm_source", type: "string", required: false, description: "UTM Source para rastreamento." },
          { name: "utm_medium", type: "string", required: false, description: "UTM Medium." },
          { name: "utm_campaign", type: "string", required: false, description: "UTM Campaign." },
          { name: "utm_term", type: "string", required: false, description: "UTM Term." },
          { name: "utm_content", type: "string", required: false, description: "UTM Content." },
        ],
        requestExample: {
          name: "Carlos Mendes",
          email: "carlos@minhaempresa.com",
          phone: "+5511988887777",
          company: "Minha Empresa LTDA",
          origin: "meta_ads",
          segment: "varejo",
          notes: "Veio do anúncio de janeiro",
          utm_source: "facebook",
          utm_campaign: "campanha-janeiro",
        },
        responseExample: {
          success: true,
          message: "Lead criado com sucesso",
          lead_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          pipe: "whatsapp",
        },
        responseFields: [
          { name: "success", type: "boolean", required: true, description: "Indica se a operação foi bem-sucedida." },
          { name: "message", type: "string", required: true, description: "Mensagem descritiva do resultado." },
          { name: "lead_id", type: "string", required: true, description: "UUID do lead criado ou unificado." },
          { name: "deduplication_method", type: "string", required: false, description: "Método usado na deduplicação: \"phone\", \"email\", ou \"name_same_day\"." },
          { name: "pipe", type: "string", required: false, description: "Funil onde o lead foi colocado: \"whatsapp\" ou \"confirmacao\"." },
        ],
        notes: [
          "Este endpoint NÃO requer autenticação — ideal para uso em automações simples.",
          "A deduplicação segue a ordem de prioridade: 1) telefone normalizado, 2) email (case-insensitive), 3) nome normalizado no mesmo dia.",
          "Se compromisso_date for preenchido, o lead é automaticamente roteado para o pipe de confirmação com status \"reuniao_marcada\".",
          "Se um lead duplicado é encontrado, os dados são mesclados: campos vazios do lead existente são preenchidos com os novos dados.",
          "Para novos projetos, recomendamos usar o endpoint lead-webhook que oferece mais funcionalidades e segurança (autenticação obrigatória).",
        ],
      },
      {
        id: "webhook-confirmacao",
        name: "Webhook Confirmação",
        description: "Endpoint legado para criação de leads diretamente no pipe de confirmação. Usado por fluxos n8n existentes para reuniões agendadas.",
        category: "webhooks",
        version: "v1",
        method: "POST",
        path: "/functions/v1/webhook-confirmacao",
        deprecated: true,
        deprecation_notice: "Use lead-webhook com place_in_pipe para o mesmo resultado. Será removido em 2027-01-01.",
        sunset_date: "2027-01-01",
        auth: {
          type: "api-key",
          header: "X-Webhook-Key",
          description: "API key da organização (obrigatória a partir de 2026-07-09)",
        },
        parameters: [
          { name: "name", type: "string", required: true, description: "Nome do lead." },
          { name: "email", type: "string", required: false, description: "Email do lead." },
          { name: "phone", type: "string", required: false, description: "Telefone do lead." },
          { name: "company", type: "string", required: false, description: "Empresa do lead." },
          { name: "sdr_id", type: "string", required: false, description: "UUID do SDR responsável." },
          { name: "closer_id", type: "string", required: false, description: "UUID do Closer responsável." },
          { name: "meeting_date", type: "string", required: false, description: "Data da reunião (ISO 8601)." },
          { name: "origin", type: "string", required: false, description: "Origem do lead. Valores válidos: \"whatsapp\", \"meta_ads\", \"outro\", \"site\", \"remarketing\", \"google_ads\", \"cal\".", defaultValue: "outro" },
        ],
        requestExample: {
          name: "Ana Oliveira",
          email: "ana@empresa.com",
          phone: "+5511977776666",
          company: "Empresa XYZ",
          sdr_id: "uuid-do-sdr",
          closer_id: "uuid-do-closer",
          meeting_date: "2026-04-15T14:00:00Z",
          origin: "meta_ads",
        },
        responseExample: {
          success: true,
          message: "Lead criado no pipe de confirmação",
          lead_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          pipe: "confirmacao",
        },
        responseFields: [
          { name: "success", type: "boolean", required: true, description: "Indica se a operação foi bem-sucedida." },
          { name: "message", type: "string", required: true, description: "Mensagem descritiva do resultado." },
          { name: "lead_id", type: "string", required: true, description: "UUID do lead criado ou atualizado." },
          { name: "pipe", type: "string", required: false, description: "Funil onde o lead foi colocado." },
        ],
        notes: [
          "Use lead-webhook com place_in_pipe para o mesmo resultado.",
          "Deduplicação automática por telefone, email, ou nome+mesmo dia.",
        ],
      },
    ],
  },
  {
    id: "leads",
    name: "Gerenciamento de Leads",
    description: "Endpoints para importação em lote, consulta de histórico e verificação de saúde da API.",
    icon: "webhook",
    endpoints: [
      {
        id: "import-leads",
        name: "Import Leads",
        description: "Importação em lote de leads via CSV/XLSX ou JSON array",
        category: "leads",
        version: "v1",
        method: "POST",
        path: "/functions/v1/import-leads",
        auth: {
          type: "api-key",
          header: "X-Webhook-Key",
          description: "Chave de API fornecida pelo administrador do sistema.",
        },
        parameters: [
          { name: "organization_id", type: "uuid", required: true, description: "UUID da organização." },
          {
            name: "leads",
            type: "array",
            required: true,
            description: "Array de objetos de lead para importação.",
            children: [
              { name: "name", type: "string", required: false, description: "Nome do lead." },
              { name: "phone", type: "string", required: false, description: "Telefone do lead." },
              { name: "email", type: "string", required: false, description: "Email do lead." },
              { name: "company", type: "string", required: false, description: "Empresa do lead." },
            ],
          },
          { name: "update_existing", type: "boolean", required: false, description: "Se true, atualiza leads existentes ao invés de ignorar duplicatas.", defaultValue: "false" },
        ],
        requestExample: {
          organization_id: "uuid-da-organizacao",
          update_existing: false,
          leads: [
            { name: "João Silva", phone: "+5511999999999", email: "joao@empresa.com", company: "Empresa A" },
            { name: "Maria Santos", phone: "+5521988887777", email: "maria@empresa.com", company: "Empresa B" },
          ],
        },
        responseExample: {
          imported: 10,
          updated: 2,
          errors: [],
        },
        responseFields: [
          { name: "imported", type: "number", required: true, description: "Quantidade de leads importados com sucesso." },
          { name: "updated", type: "number", required: true, description: "Quantidade de leads atualizados (quando update_existing=true)." },
          { name: "errors", type: "array", required: true, description: "Lista de erros encontrados durante a importação." },
        ],
        notes: [
          "Máximo de 1000 leads por requisição",
          "Deduplicação automática por telefone, email, ou nome+data",
        ],
      },
      {
        id: "get-lead-timeline",
        name: "Get Lead Timeline",
        description: "Retorna o histórico completo de ações e eventos de um lead",
        category: "leads",
        version: "v1",
        method: "GET",
        path: "/functions/v1/get-lead-timeline",
        auth: {
          type: "bearer",
          header: "Authorization",
          description: "JWT token no header Authorization: Bearer <token>.",
        },
        parameters: [
          { name: "lead_id", type: "uuid", required: true, description: "UUID do lead." },
          { name: "page", type: "number", required: false, description: "Número da página para paginação.", defaultValue: "0" },
          { name: "limit", type: "number", required: false, description: "Quantidade de eventos por página.", defaultValue: "50" },
        ],
        requestExample: {
          lead_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          page: 0,
          limit: 50,
        },
        responseExample: {
          timeline: [
            { type: "created", timestamp: "2026-04-01T10:00:00Z", description: "Lead criado via meta_ads" },
            { type: "stage_change", timestamp: "2026-04-02T14:30:00Z", description: "Movido para 'abordado'" },
            { type: "message_sent", timestamp: "2026-04-02T14:35:00Z", description: "Mensagem enviada pelo Copilot" },
          ],
          page: 0,
          limit: 50,
          total: 3,
        },
        responseFields: [
          { name: "timeline", type: "array", required: true, description: "Lista de eventos do lead em ordem cronológica." },
          { name: "page", type: "number", required: true, description: "Página atual." },
          { name: "limit", type: "number", required: true, description: "Limite de eventos por página." },
          { name: "total", type: "number", required: true, description: "Total de eventos do lead." },
        ],
        notes: [
          "Requer autenticação JWT",
          "Paginação via page/limit",
        ],
      },
      {
        id: "check-api-health",
        name: "Check API Health",
        description: "Verifica o status da API e conexão com o banco de dados",
        category: "leads",
        version: "v1",
        method: "GET",
        path: "/functions/v1/check-api-health",
        auth: {
          type: "bearer",
          header: "Authorization",
          description: "JWT token no header Authorization: Bearer <token>.",
        },
        parameters: [],
        requestExample: {},
        responseExample: {
          status: "healthy",
          database: "connected",
          latency_ms: 12,
        },
        responseFields: [
          { name: "status", type: "string", required: true, description: "Status da API: \"healthy\" ou \"degraded\"." },
          { name: "database", type: "string", required: true, description: "Status da conexão com o banco: \"connected\" ou \"disconnected\"." },
          { name: "latency_ms", type: "number", required: true, description: "Latência da conexão com o banco em milissegundos." },
        ],
        notes: [
          "Disponível apenas para administradores",
        ],
      },
    ],
  },
];
