import { ApiCategory, ApiEndpoint } from "./types";

// Public REST API v1 (ADR-0008). Single source of truth for the in-app docs,
// code generators, and the OpenAPI/Postman/llms.txt artifacts (see
// scripts/gen-api-spec.ts). Base path: /functions/v1/api + /api/v1/* routes.

const auth = {
  type: "api-key" as const,
  header: "X-API-Key",
  description:
    "API Key escopada gerada em Configurações > API Keys (tq_live_*). Cada key pertence a uma organização — você nunca envia organization_id. Envie no header X-API-Key (ou Authorization: Bearer tq_live_...).",
};

const listEnvelopeNote =
  "Listas retornam { data, next_cursor, has_more }. Pagine passando next_cursor de volta em ?cursor=. Erros: { error: { code, message, details? } }.";

const leadIdParam = {
  name: "id",
  type: "string (uuid)",
  required: true,
  description: "ID do lead (path).",
};

const endpoints: ApiEndpoint[] = [
  {
    id: "api-ping",
    name: "Ping",
    description: "Smoke check autenticado. Confirma que a API Key é válida e retorna a organização vinculada. Não exige escopo específico.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/ping",
    auth,
    parameters: [],
    requestExample: {},
    responseExample: { pong: true, organization_id: "6030520a-2ca7-477d-be89-55758e2cd808", timestamp: "2026-06-14T19:05:04.767Z" },
    responseFields: [
      { name: "pong", type: "boolean", required: true, description: "Sempre true." },
      { name: "organization_id", type: "string", required: true, description: "Org resolvida da API Key." },
      { name: "timestamp", type: "string", required: true, description: "ISO 8601." },
    ],
  },
  {
    id: "api-list-leads",
    name: "Listar leads",
    description: "Lista leads com paginação keyset (cursor) e filtros flat. Cada item traz tier efetivo, tags, responsáveis e se foi vendido (+ valor). Escopo: lead:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/leads",
    auth,
    parameters: [
      { name: "stage", type: "string", required: false, description: "Etapas (csv). Lead com entry em qualquer pipe nessas etapas. Ex: \"novo,abordado\"." },
      { name: "tier", type: "string", required: false, description: "Tier efetivo (csv): diamante, ouro, prata, bronze, desqualificado." },
      { name: "tag", type: "string", required: false, description: "Nomes de tag (csv, case-insensitive)." },
      { name: "origin", type: "string", required: false, description: "Origem (csv)." },
      { name: "responsible_id", type: "string (uuid)", required: false, description: "Casa responsible/sdr/closer/pré-vendas/vendas." },
      { name: "created_from", type: "string", required: false, description: "created_at >= (ISO 8601)." },
      { name: "created_to", type: "string", required: false, description: "created_at <= (ISO 8601)." },
      { name: "q", type: "string", required: false, description: "Busca em nome, empresa, email, telefone." },
      { name: "limit", type: "number", required: false, description: "1–100. Default 50.", defaultValue: "50" },
      { name: "cursor", type: "string", required: false, description: "next_cursor da página anterior (opaco)." },
    ],
    requestExample: {},
    responseExample: {
      data: [{ id: "f21072f1-…", name: "Nairde", company: "Valim", origin: "outro", tier: "ouro", tags: [{ id: "t1", name: "VIP", color: "#F5C518" }], responsible_id: "bf98…", sdr_id: null, closer_id: null, sold: false, sale_value: null, rating: 4, qualification_score: 80, created_at: "2026-06-14T14:30:22Z" }],
      next_cursor: "eyJjIjoi…",
      has_more: true,
    },
    responseFields: [
      { name: "data", type: "object[]", required: true, description: "Página de leads.", children: [
        { name: "id", type: "string", required: true, description: "ID do lead." },
        { name: "tier", type: "string", required: false, description: "Tier efetivo (qualification ?? pre_qualification)." },
        { name: "tags", type: "object[]", required: true, description: "{ id, name, color }." },
        { name: "sold", type: "boolean", required: true, description: "Vendido (Negócio em etapa de ganho — stage_role won — em qualquer funil)." },
        { name: "sale_value", type: "number", required: false, description: "Valor da venda (se houver)." },
      ] },
      { name: "next_cursor", type: "string|null", required: true, description: "Cursor da próxima página, ou null." },
      { name: "has_more", type: "boolean", required: true, description: "Existe próxima página." },
    ],
    notes: [listEnvelopeNote, "Ordenação fixa: created_at desc, id desc."],
    rateLimits: "Por API Key (default 100/min).",
  },
  {
    id: "api-get-lead",
    name: "Lead 360",
    description: "Retorna um lead completo: tier, tags, custom fields (valores), responsáveis e posições em todos os pipes (com vendido/valor). 404 se não existir na org. Escopo: lead:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/leads/{id}",
    auth,
    parameters: [leadIdParam],
    requestExample: {},
    responseExample: { id: "f21072f1-…", name: "Nairde", company: "Valim", email: null, phone: "+5511…", origin: "outro", tier: "ouro", rating: 4, qualification_score: 80, responsible_id: "bf98…", sdr_id: null, closer_id: null, pre_sale_responsible_id: null, sale_responsible_id: null, tags: [{ id: "t1", name: "VIP", color: "#F5C518" }], custom_fields: [{ field_name: "faturamento", field_type: "text", value: "5M" }], pipes: [{ pipeline: "vendas", pipeline_name: "Funil de Vendas", type: "custom", stage_key: "novo", sold: false, sale_value: null, entered_at: "2026-06-14T14:30:22Z", stage_changed_at: "2026-06-14T14:30:22Z" }], created_at: "2026-06-14T14:30:22Z", updated_at: "2026-06-14T14:30:22Z" },
    responseFields: [
      { name: "tags", type: "object[]", required: true, description: "{ id, name, color }." },
      { name: "custom_fields", type: "object[]", required: true, description: "{ field_name, field_type, value }." },
      { name: "pipes", type: "object[]", required: true, description: "Posições em pipes: { pipeline, stage_key, sold, sale_value, … }." },
    ],
  },
  {
    id: "api-lead-timeline",
    name: "Timeline do lead",
    description: "Histórico do lead (lead_history) com paginação keyset. Escopo: lead:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/leads/{id}/timeline",
    auth,
    parameters: [
      leadIdParam,
      { name: "limit", type: "number", required: false, description: "1–100. Default 50.", defaultValue: "50" },
      { name: "cursor", type: "string", required: false, description: "next_cursor da página anterior." },
    ],
    requestExample: {},
    responseExample: { data: [{ id: "e1", created_at: "2026-06-14T14:30:22Z", action: "lead_created", description: "Lead criado", source: "api", entity_type: null, entity_id: null, metadata: {} }], next_cursor: null, has_more: false },
    responseFields: [
      { name: "data", type: "object[]", required: true, description: "Eventos { id, created_at, action, description, source, entity_type, entity_id, metadata }." },
      { name: "next_cursor", type: "string|null", required: true, description: "Cursor da próxima página." },
      { name: "has_more", type: "boolean", required: true, description: "Existe próxima página." },
    ],
    notes: [listEnvelopeNote],
  },
  {
    id: "api-list-pipelines",
    name: "Listar funis",
    description: "Catálogo de funis com etapas, de sistema e personalizados. Escopo: pipeline:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/pipelines",
    auth,
    parameters: [
      { name: "pipeline", type: "string", required: false, description: "Devolve só um funil. Aceita o slug ou o id de qualquer funil da organização. Funil inexistente devolve lista vazia." },
      { name: "only_active_stages", type: "boolean", required: false, description: "Com \"true\", cada funil traz apenas as etapas ativas — as mesmas que o cliente vê no kanban. Sem o parâmetro, vêm todas, inclusive as desativadas." },
    ],
    requestExample: {},
    responseExample: { data: [{ id: "p1", name: "Funil de Vendas", slug: "vendas", type: "custom", color: "#f59e0b", icon: "trending-up", display_order: 3, is_active: true, stages: [{ stage_key: "novo", name: "Novo", color: "#888", position: 0, is_active: true, is_final_positive: false, is_final_negative: false }] }], next_cursor: null, has_more: false },
    responseFields: [
      { name: "data", type: "object[]", required: true, description: "Funis com stages embutidos." },
    ],
    notes: [
      "Catálogo sem paginação (next_cursor sempre null).",
      "Etapa desativada existe no banco e é aceita pela API, mas não aparece no kanban: um Negócio aberto nela fica invisível na tela. Para montar seletor, use only_active_stages=true.",
    ],
  },
  {
    id: "api-create-custom-field",
    name: "Criar campo personalizado",
    description: "Cadastra um campo personalizado de Lead. Idempotente por nome, ignorando maiúsculas: pedir um campo que já existe devolve o existente com created=false, em vez de criar uma segunda grafia. Escopo: metadata:write.",
    category: "rest-api",
    version: "v1",
    method: "POST",
    path: "/api/v1/custom-fields",
    auth,
    parameters: [],
    requestExample: { field_name: "faturamento_mensal", field_type: "number" },
    responseExample: { id: "cf1", field_name: "faturamento_mensal", field_type: "number", created: true },
    responseFields: [
      { name: "field_name", type: "string", required: true, description: "Nome como está gravado — use exatamente este ao enviar valores." },
      { name: "created", type: "boolean", required: true, description: "true quando o campo nasceu agora; false quando já existia." },
    ],
    notes: [
      "field_type aceita text, number, date, select e boolean. O tipo select exige field_options com ao menos uma opção.",
      "201 quando cria, 200 quando o campo já existia.",
      "Campo personalizado é do Lead. Negócio não tem campos personalizados.",
    ],
  },
  {
    id: "api-list-team-members",
    name: "Listar membros da equipe",
    description: "Catálogo de membros da organização, para resolver os IDs usados nos campos de responsável (owner_id do Negócio; responsible_id, sale_responsible_id e pre_sale_responsible_id do Lead). Não expõe telefone nem dados de remuneração. Escopo: team:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/team-members",
    auth,
    parameters: [],
    requestExample: {},
    responseExample: { data: [{ id: "tm1", name: "Maria Souza", email: "maria@empresa.com", job_title: "Closer", role: "member", is_active: true }], next_cursor: null, has_more: false },
    responseFields: [
      { name: "data", type: "object[]", required: true, description: "Membros, ativos primeiro, depois por nome." },
    ],
    notes: [
      "Uma lista só serve pré-venda e vendas: o Torque não marca no membro quem é o quê — isso é decidido por Lead, e a mesma pessoa pode ser pré-venda num e vendas em outro.",
      "job_title é texto livre (Closer, SDR, CEO…) e serve como dica na tela, não como filtro.",
      "Inclui inativos, com is_active=false: seletor quer os ativos, mas quem sincroniza histórico precisa resolver o nome de quem já saiu.",
    ],
  },
  {
    id: "api-list-tags",
    name: "Listar tags",
    description: "Catálogo de tags da organização. Escopo: metadata:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/tags",
    auth,
    parameters: [],
    requestExample: {},
    responseExample: { data: [{ id: "t1", name: "VIP", color: "#F5C518" }], next_cursor: null, has_more: false },
    responseFields: [{ name: "data", type: "object[]", required: true, description: "{ id, name, color }." }],
  },
  {
    id: "api-list-custom-fields",
    name: "Listar custom fields",
    description: "Catálogo de definições de campos customizados. Escopo: metadata:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/custom-fields",
    auth,
    parameters: [],
    requestExample: {},
    responseExample: { data: [{ id: "cf1", field_name: "faturamento", field_type: "text", field_options: null, is_required: false, display_order: 0 }], next_cursor: null, has_more: false },
    responseFields: [{ name: "data", type: "object[]", required: true, description: "{ id, field_name, field_type, field_options, is_required, display_order }." }],
  },
  {
    id: "api-patch-lead",
    name: "Editar lead",
    description: "Atualiza campos do Lead. Além de nome, empresa, e-mail, telefone e observações, aceita segment, faturamento e os cinco utm_* — que são colunas próprias de leads, não campos personalizados. Escopo: lead:write.",
    category: "rest-api",
    version: "v1",
    method: "PATCH",
    path: "/api/v1/leads/{id}",
    auth,
    parameters: [
      leadIdParam,
      { name: "name", type: "string", required: false, description: "Nome." },
      { name: "company", type: "string", required: false, description: "Empresa." },
      { name: "email", type: "string", required: false, description: "Email." },
      { name: "phone", type: "string", required: false, description: "Telefone." },
      { name: "notes", type: "string", required: false, description: "Observações." },
      { name: "rating", type: "number", required: false, description: "Avaliação (numérico)." },
      { name: "qualification_score", type: "number", required: false, description: "Score 0–100." },
      { name: "tier", type: "string", required: false, description: "qualification_tier: diamante|ouro|prata|bronze|desqualificado." },
      { name: "pre_qualification_tier", type: "string", required: false, description: "Mesmos valores de tier." },
      { name: "responsible_id", type: "string (uuid)", required: false, description: "Responsável (deve pertencer à org)." },
      { name: "sdr_id", type: "string (uuid)", required: false, description: "Pré-vendas." },
      { name: "closer_id", type: "string (uuid)", required: false, description: "Closer." },
    ],
    requestExample: { name: "Acme Renomeado", tier: "ouro", rating: 5 },
    responseExample: { id: "f21072f1-…", name: "Acme Renomeado", tier: "ouro", rating: 5 },
    responseFields: [{ name: "(lead 360)", type: "object", required: true, description: "Lead atualizado, mesmo shape de GET /leads/{id}." }],
    notes: [
      "422 invalid_tier para tier fora do enum. 422 invalid_responsible se o responsável não pertence à org. 422 no_valid_fields se nenhum campo editável foi enviado.",
      "Campos de negócio como segmento/faturamento/urgência são custom fields — use PUT /custom-fields.",
    ],
  },
  {
    id: "api-move-stage",
    name: "Mover etapa",
    description: "Move o lead para uma etapa de um funil. Dispara as mesmas automações da UI (workflows, meeting_events, transição automática ao funil de destino no compareceu). Escopo: lead:write.",
    category: "rest-api",
    version: "v1",
    method: "POST",
    path: "/api/v1/leads/{id}/stage",
    deprecated: true,
    deprecation_notice: "Move um LEAD para uma etapa — e no modelo atual um Lead nunca tem etapa; quem ocupa etapa é o Negócio. Use POST /api/v1/deals/{id}/move.",
    auth,
    parameters: [
      leadIdParam,
      { name: "pipe", type: "string", required: false, description: "Slug ou id de qualquer funil da organização. Default: o funil padrão da organização.", defaultValue: "funil padrão da organização" },
      { name: "stage", type: "string", required: true, description: "stage_key de destino (validado contra as etapas do funil)." },
    ],
    requestExample: { pipe: "vendas", stage: "proposta_enviada" },
    responseExample: { moved: true, target_stage: "proposta_enviada", target_pipe: "vendas" },
    responseFields: [{ name: "moved", type: "boolean", required: true, description: "Sempre true em sucesso." }],
    notes: ["400 missing_stage sem stage. 404 se o lead não for da org. 422 stage_move_failed para etapa inválida (a mensagem lista as válidas).", "meeting_date não é suportado no v1."],
  },
  {
    id: "api-add-tags",
    name: "Adicionar tags",
    description: "Adiciona tags por nome ao lead, criando as que não existem. Escopo: lead:write.",
    category: "rest-api",
    version: "v1",
    method: "POST",
    path: "/api/v1/leads/{id}/tags",
    auth,
    parameters: [
      leadIdParam,
      { name: "tags", type: "string[]", required: true, description: "Nomes de tag. Ex: [\"VIP\", \"Quente\"]." },
    ],
    requestExample: { tags: ["VIP", "Quente"] },
    responseExample: { tags: [{ id: "t1", name: "VIP", color: "#F5C518" }, { id: "t2", name: "Quente", color: "#F5C518" }] },
    responseFields: [{ name: "tags", type: "object[]", required: true, description: "Tags atuais do lead." }],
    notes: ["400 se tags não for array. 404 se o lead não for da org."],
  },
  {
    id: "api-remove-tag",
    name: "Remover tag",
    description: "Remove uma tag (por nome) do lead. Idempotente. Escopo: lead:write.",
    category: "rest-api",
    version: "v1",
    method: "DELETE",
    path: "/api/v1/leads/{id}/tags/{tag}",
    auth,
    parameters: [
      leadIdParam,
      { name: "tag", type: "string", required: true, description: "Nome da tag (path, case-insensitive)." },
    ],
    requestExample: {},
    responseExample: { removed: true },
    responseFields: [{ name: "removed", type: "boolean", required: true, description: "Sempre true." }],
    notes: ["404 se o lead não for da org."],
  },
  {
    id: "api-put-custom-fields",
    name: "Setar custom fields",
    description: "Define valores de campos customizados existentes. Não cria campos novos no v1. Escopo: lead:write.",
    category: "rest-api",
    version: "v1",
    method: "PUT",
    path: "/api/v1/leads/{id}/custom-fields",
    auth,
    parameters: [
      { name: "create_missing", type: "boolean", required: false, description: "Com \"true\", cria como texto o campo que ainda não existe em vez de recusar com 422. Sem o parâmetro, campo desconhecido continua sendo recusado." },
    ],
    requestExample: { faturamento: "5M", segmento: "varejo" },
    responseExample: { updated: true },
    responseFields: [{ name: "updated", type: "boolean", required: true, description: "Sempre true em sucesso." }],
    notes: ["422 unknown_field (com details.unknown_fields) se algum campo não existe na org — nada é gravado. 404 se o lead não for da org."],
  },
  // ── Negócio ───────────────────────────────────────────────────────────────
  //
  // Negócio, na interface, é `deal` na API. Quem chega do Kommo precisa saber
  // que lá "lead" é o card que anda no funil — aqui não: seguimos o Pipedrive,
  // Lead é a pessoa e Negócio é o que anda.
  {
    id: "api-create-lead",
    name: "Criar lead",
    description: "Cria um Lead. Telefone repetido NÃO cria uma segunda pessoa: responde 409 com o id de quem já está lá. Escopo: lead:write.",
    category: "rest-api",
    version: "v1",
    method: "POST",
    path: "/api/v1/leads",
    auth,
    parameters: [
      { name: "name", type: "string", required: true, description: "Nome do lead." },
      { name: "phone", type: "string", required: false, description: "Telefone. É a chave de deduplicação." },
      { name: "email", type: "string", required: false, description: "E-mail." },
      { name: "company", type: "string", required: false, description: "Empresa." },
      { name: "Idempotency-Key", type: "string", required: false, description: "Cabeçalho. Mesma chave devolve o MESMO Lead (200) em vez de criar outro (201)." },
    ],
    requestExample: { name: "João", phone: "11999990000" },
    responseExample: { id: "9f1c…", name: "João", phone: "11999990000" },
    responseFields: [{ name: "id", type: "string", required: true, description: "Identificador do Lead." }],
    notes: [
      "409 lead_already_exists quando o telefone já existe na org — o corpo traz details.lead_id e details.name. Siga para POST /api/v1/deals com aquele lead_id.",
      "Retentativa com a mesma Idempotency-Key devolve 200 e o mesmo Lead: nada é criado duas vezes.",
    ],
  },
  {
    id: "api-search-leads",
    name: "Buscar lead",
    description: "Lookup por telefone ou e-mail, para deduplicar antes de criar. Escopo: lead:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/leads/search",
    auth,
    parameters: [
      { name: "phone", type: "string", required: false, description: "Telefone a procurar." },
      { name: "email", type: "string", required: false, description: "E-mail a procurar (insensível a caixa)." },
    ],
    requestExample: {},
    responseExample: { data: [{ id: "9f1c…", name: "João" }], next_cursor: null, has_more: false },
    responseFields: [{ name: "data", type: "object[]", required: true, description: "Leads que casam. LISTA, porque um telefone pode casar mais de um." }],
    notes: ["422 missing_search_criteria sem phone nem email — busca sem alvo seria varredura. Para a base inteira use GET /api/v1/leads."],
  },
  {
    id: "api-list-deals",
    name: "Listar negócios",
    description: "Lista Negócios com filtros e cursor. Use updated_since para sincronizar só o que mudou. Escopo: deal:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/deals",
    auth,
    parameters: [
      { name: "pipeline", type: "string", required: false, description: "Slug do funil. Ex: \"vendas\"." },
      { name: "stage", type: "string", required: false, description: "Etapa." },
      { name: "owner_id", type: "string", required: false, description: "Responsável." },
      { name: "status", type: "string", required: false, description: "open | won | lost | all." },
      { name: "updated_since", type: "string", required: false, description: "ISO 8601. Traz o que teve atividade depois — INCLUSIVE quem só mudou de etapa." },
      { name: "cursor", type: "string", required: false, description: "Devolva o next_cursor da página anterior." },
    ],
    requestExample: {},
    responseExample: { data: [{ id: "d1…", title: "Reposição", pipeline: "vendas", stage: "proposta_enviada", source: "api" }], next_cursor: null, has_more: false },
    responseFields: [
      { name: "source", type: "string", required: true, description: "Procedência: por qual porta o Negócio nasceu — human, workflow, api, import ou backfill." },
      { name: "last_activity_at", type: "string", required: true, description: "Quando algo aconteceu com ele — edição OU mudança de posição. É a chave de updated_since." },
    ],
    notes: ["422 invalid_updated_since para data ilegível. Nunca devolve a base inteira nesse caso."],
  },
  {
    id: "api-create-deal",
    name: "Abrir negócio",
    description: "Abre um Negócio para um Lead que JÁ existe. Escopo: deal:write.",
    category: "rest-api",
    version: "v1",
    method: "POST",
    path: "/api/v1/deals",
    auth,
    parameters: [
      { name: "lead_id", type: "string", required: true, description: "Lead existente. Crie antes com POST /api/v1/leads." },
      { name: "pipeline", type: "string", required: true, description: "Slug do funil." },
      { name: "stage", type: "string", required: true, description: "Etapa inicial." },
      { name: "title", type: "string", required: false, description: "Título. Sem ele, vira \"Negócio de <mês>/<ano>\"." },
      { name: "value", type: "number", required: false, description: "Valor." },
      { name: "owner_id", type: "string", required: false, description: "Responsável." },
    ],
    requestExample: { lead_id: "9f1c…", pipeline: "vendas", stage: "novo", value: 1200 },
    responseExample: { id: "d1…", source: "api", warning: { code: "lead_has_open_deal_in_pipeline", open_deal_id: "d0…" } },
    responseFields: [{ name: "warning", type: "object", required: false, description: "Presente quando o Lead JÁ tinha Negócio aberto neste funil. Não impede — avisa." }],
    notes: [
      "422 inline_lead_not_supported se você mandar o Lead embutido: a criação é estrita, crie a pessoa antes.",
      "Abrir um segundo Negócio no mesmo funil funciona — é assim que recompra se representa.",
    ],
  },
  {
    id: "api-get-deal",
    name: "Ler negócio",
    description: "Devolve o Negócio com a posição atual. Escopo: deal:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/deals/{id}",
    auth,
    parameters: [{ name: "id", type: "string", required: true, description: "Identificador do Negócio (no caminho)." }],
    requestExample: {},
    responseExample: { id: "d1…", pipeline: "vendas", stage: "proposta_enviada", source: "api" },
    responseFields: [{ name: "pipeline", type: "string", required: true, description: "Funil onde está agora." }],
    notes: ["404 para Negócio de outra organização, igual a inexistente."],
  },
  {
    id: "api-update-deal",
    name: "Editar negócio",
    description: "Título, valor, dono e fechamento com motivo. Não move e não reabre. Escopo: deal:write.",
    category: "rest-api",
    version: "v1",
    method: "PATCH",
    path: "/api/v1/deals/{id}",
    auth,
    parameters: [
      { name: "title", type: "string", required: false, description: "Novo título." },
      { name: "value", type: "number", required: false, description: "Novo valor." },
      { name: "owner_id", type: "string", required: false, description: "Novo responsável." },
      { name: "status", type: "string", required: false, description: "open | won | lost." },
      { name: "loss_reason", type: "string", required: false, description: "Motivo, quando status = lost." },
    ],
    requestExample: { status: "lost", loss_reason: "Preço" },
    responseExample: { id: "d1…", won: false, loss_reason: "Preço" },
    responseFields: [{ name: "closed_at", type: "string", required: false, description: "Preenchido ao fechar." }],
    notes: [
      "422 stage_not_editable se mandar stage ou pipeline: posição tem rota própria.",
      "Negócio fechado NÃO reabre — reverter venda é irreversível.",
      "Campo omitido mantém o valor atual. Não há como limpar campo por esta rota.",
    ],
  },
  {
    id: "api-move-deal",
    name: "Mover negócio",
    description: "Move o Negócio de etapa ou de funil. Mover é MOVER: nada fica para trás. Escopo: deal:write.",
    category: "rest-api",
    version: "v1",
    method: "POST",
    path: "/api/v1/deals/{id}/move",
    auth,
    parameters: [
      { name: "pipeline", type: "string", required: true, description: "Funil de destino." },
      { name: "stage", type: "string", required: true, description: "Etapa de destino." },
      { name: "owner_id", type: "string", required: false, description: "Responsável no destino." },
    ],
    requestExample: { pipeline: "vendas", stage: "proposta_enviada" },
    responseExample: { id: "d1…", pipeline: "vendas", stage: "proposta_enviada" },
    responseFields: [{ name: "pipeline", type: "string", required: true, description: "A posição NOVA." }],
    notes: [
      "422 custom_pipeline_not_supported para destino em funil customizado: o card mudaria de identidade e perderia o histórico.",
      "404 também quando o Negócio não tem posição em funil nenhum — não há o que mover.",
    ],
  },
  {
    id: "api-list-lead-deals",
    name: "Negócios de um lead",
    description: "Todos os Negócios daquela pessoa, abertos primeiro. Escopo: deal:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/leads/{id}/deals",
    auth,
    parameters: [leadIdParam],
    requestExample: {},
    responseExample: { data: [{ id: "d1…", pipeline: "vendas", stage: "novo" }], next_cursor: null, has_more: false },
    responseFields: [{ name: "data", type: "object[]", required: true, description: "Negócios do Lead, cada um com a própria posição." }],
    notes: ["É por esta lista que a recompra fica legível: o mesmo Lead pode ter dois Negócios abertos no mesmo funil."],
  },
];

export const restApiCategory: ApiCategory = {
  id: "rest-api",
  name: "REST API v1",
  description: "API REST pública (/api/v1/*). Lead é a pessoa; Negócio (`deal`) é a venda que anda pelo funil. Se você vem do Kommo: lá \"lead\" é o card do funil — aqui esse papel é do Negócio. Leitura e escrita escopadas por API Key. Base: /functions/v1/api.",
  icon: "code",
  endpoints,
};
