import { ApiCategory, ApiEndpoint } from "./types";

// Public REST API v1 (ADR-0008). Single source of truth for the in-app docs,
// code generators, and the OpenAPI/Postman/llms.txt artifacts (see
// scripts/gen-api-spec.ts). Base path: /functions/v1/api + /api/v1/* routes.

const auth = {
  type: "api-key" as const,
  header: "X-API-Key",
  description:
    "API Key escopada gerada em Configurações > API Keys (tq_live_*). Cada key pertence a uma organização — você nunca envia organization_id. Envie no header X-API-Key (ou Authorization: Bearer tq_live_...).",
};

const listEnvelopeNote =
  "Listas retornam { data, next_cursor, has_more }. Pagine passando next_cursor de volta em ?cursor=. Erros: { error: { code, message, details? } }.";

const leadIdParam = {
  name: "id",
  type: "string (uuid)",
  required: true,
  description: "ID do lead (path).",
};

const endpoints: ApiEndpoint[] = [
  {
    id: "api-ping",
    name: "Ping",
    description: "Smoke check autenticado. Confirma que a API Key é válida e retorna a organização vinculada. Não exige escopo específico.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/ping",
    auth,
    parameters: [],
    requestExample: {},
    responseExample: { pong: true, organization_id: "6030520a-2ca7-477d-be89-55758e2cd808", timestamp: "2026-06-14T19:05:04.767Z" },
    responseFields: [
      { name: "pong", type: "boolean", required: true, description: "Sempre true." },
      { name: "organization_id", type: "string", required: true, description: "Org resolvida da API Key." },
      { name: "timestamp", type: "string", required: true, description: "ISO 8601." },
    ],
  },
  {
    id: "api-list-leads",
    name: "Listar leads",
    description: "Lista leads com paginação keyset (cursor) e filtros flat. Cada item traz tier efetivo, tags, responsáveis e se foi vendido (+ valor). Escopo: lead:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/leads",
    auth,
    parameters: [
      { name: "stage", type: "string", required: false, description: "Etapas (csv). Lead com entry em qualquer pipe nessas etapas. Ex: \"novo,abordado\"." },
      { name: "tier", type: "string", required: false, description: "Tier efetivo (csv): diamante, ouro, prata, bronze, desqualificado." },
      { name: "tag", type: "string", required: false, description: "Nomes de tag (csv, case-insensitive)." },
      { name: "origin", type: "string", required: false, description: "Origem (csv)." },
      { name: "responsible_id", type: "string (uuid)", required: false, description: "Casa responsible/sdr/closer/pré-vendas/vendas." },
      { name: "created_from", type: "string", required: false, description: "created_at >= (ISO 8601)." },
      { name: "created_to", type: "string", required: false, description: "created_at <= (ISO 8601)." },
      { name: "q", type: "string", required: false, description: "Busca em nome, empresa, email, telefone." },
      { name: "limit", type: "number", required: false, description: "1–100. Default 50.", defaultValue: "50" },
      { name: "cursor", type: "string", required: false, description: "next_cursor da página anterior (opaco)." },
    ],
    requestExample: {},
    responseExample: {
      data: [{ id: "f21072f1-…", name: "Nairde", company: "Valim", origin: "outro", tier: "ouro", tags: [{ id: "t1", name: "VIP", color: "#F5C518" }], responsible_id: "bf98…", sdr_id: null, closer_id: null, sold: false, sale_value: null, rating: 4, qualification_score: 80, created_at: "2026-06-14T14:30:22Z" }],
      next_cursor: "eyJjIjoi…",
      has_more: true,
    },
    responseFields: [
      { name: "data", type: "object[]", required: true, description: "Página de leads.", children: [
        { name: "id", type: "string", required: true, description: "ID do lead." },
        { name: "tier", type: "string", required: false, description: "Tier efetivo (qualification ?? pre_qualification)." },
        { name: "tags", type: "object[]", required: true, description: "{ id, name, color }." },
        { name: "sold", type: "boolean", required: true, description: "Vendido (etapa vendido em propostas)." },
        { name: "sale_value", type: "number", required: false, description: "Valor da venda (se houver)." },
      ] },
      { name: "next_cursor", type: "string|null", required: true, description: "Cursor da próxima página, ou null." },
      { name: "has_more", type: "boolean", required: true, description: "Existe próxima página." },
    ],
    notes: [listEnvelopeNote, "Ordenação fixa: created_at desc, id desc."],
    rateLimits: "Por API Key (default 100/min).",
  },
  {
    id: "api-get-lead",
    name: "Lead 360",
    description: "Retorna um lead completo: tier, tags, custom fields (valores), responsáveis e posições em todos os pipes (com vendido/valor). 404 se não existir na org. Escopo: lead:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/leads/{id}",
    auth,
    parameters: [leadIdParam],
    requestExample: {},
    responseExample: { id: "f21072f1-…", name: "Nairde", company: "Valim", email: null, phone: "+5511…", origin: "outro", tier: "ouro", rating: 4, qualification_score: 80, responsible_id: "bf98…", sdr_id: null, closer_id: null, pre_sale_responsible_id: null, sale_responsible_id: null, tags: [{ id: "t1", name: "VIP", color: "#F5C518" }], custom_fields: [{ field_name: "faturamento", field_type: "text", value: "5M" }], pipes: [{ pipeline: "whatsapp", pipeline_name: "WhatsApp", type: "system", stage_key: "novo", sold: false, sale_value: null, entered_at: "2026-06-14T14:30:22Z", stage_changed_at: "2026-06-14T14:30:22Z" }], created_at: "2026-06-14T14:30:22Z", updated_at: "2026-06-14T14:30:22Z" },
    responseFields: [
      { name: "tags", type: "object[]", required: true, description: "{ id, name, color }." },
      { name: "custom_fields", type: "object[]", required: true, description: "{ field_name, field_type, value }." },
      { name: "pipes", type: "object[]", required: true, description: "Posições em pipes: { pipeline, stage_key, sold, sale_value, … }." },
    ],
  },
  {
    id: "api-lead-timeline",
    name: "Timeline do lead",
    description: "Histórico do lead (lead_history) com paginação keyset. Escopo: lead:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/leads/{id}/timeline",
    auth,
    parameters: [
      leadIdParam,
      { name: "limit", type: "number", required: false, description: "1–100. Default 50.", defaultValue: "50" },
      { name: "cursor", type: "string", required: false, description: "next_cursor da página anterior." },
    ],
    requestExample: {},
    responseExample: { data: [{ id: "e1", created_at: "2026-06-14T14:30:22Z", action: "lead_created", description: "Lead criado", source: "api", entity_type: null, entity_id: null, metadata: {} }], next_cursor: null, has_more: false },
    responseFields: [
      { name: "data", type: "object[]", required: true, description: "Eventos { id, created_at, action, description, source, entity_type, entity_id, metadata }." },
      { name: "next_cursor", type: "string|null", required: true, description: "Cursor da próxima página." },
      { name: "has_more", type: "boolean", required: true, description: "Existe próxima página." },
    ],
    notes: [listEnvelopeNote],
  },
  {
    id: "api-list-pipelines",
    name: "Listar funis",
    description: "Catálogo de funis com etapas. Funis system trazem etapas; funis custom vêm com stages vazio no v1. Escopo: pipeline:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/pipelines",
    auth,
    parameters: [],
    requestExample: {},
    responseExample: { data: [{ id: "p1", name: "WhatsApp", slug: "whatsapp", type: "system", color: "#25D366", icon: "message-circle", display_order: 1, is_active: true, stages: [{ stage_key: "novo", name: "Novo", color: "#888", position: 0, is_active: true, is_final_positive: false, is_final_negative: false }] }], next_cursor: null, has_more: false },
    responseFields: [
      { name: "data", type: "object[]", required: true, description: "Funis com stages embutidos." },
    ],
    notes: ["Catálogo sem paginação (next_cursor sempre null)."],
  },
  {
    id: "api-list-tags",
    name: "Listar tags",
    description: "Catálogo de tags da organização. Escopo: metadata:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/tags",
    auth,
    parameters: [],
    requestExample: {},
    responseExample: { data: [{ id: "t1", name: "VIP", color: "#F5C518" }], next_cursor: null, has_more: false },
    responseFields: [{ name: "data", type: "object[]", required: true, description: "{ id, name, color }." }],
  },
  {
    id: "api-list-custom-fields",
    name: "Listar custom fields",
    description: "Catálogo de definições de campos customizados. Escopo: metadata:read.",
    category: "rest-api",
    version: "v1",
    method: "GET",
    path: "/api/v1/custom-fields",
    auth,
    parameters: [],
    requestExample: {},
    responseExample: { data: [{ id: "cf1", field_name: "faturamento", field_type: "text", field_options: null, is_required: false, display_order: 0 }], next_cursor: null, has_more: false },
    responseFields: [{ name: "data", type: "object[]", required: true, description: "{ id, field_name, field_type, field_options, is_required, display_order }." }],
  },
  {
    id: "api-patch-lead",
    name: "Editar lead",
    description: "Atualização parcial de campos permitidos. Campos não-allowlistados são ignorados. Escopo: lead:write.",
    category: "rest-api",
    version: "v1",
    method: "PATCH",
    path: "/api/v1/leads/{id}",
    auth,
    parameters: [
      leadIdParam,
      { name: "name", type: "string", required: false, description: "Nome." },
      { name: "company", type: "string", required: false, description: "Empresa." },
      { name: "email", type: "string", required: false, description: "Email." },
      { name: "phone", type: "string", required: false, description: "Telefone." },
      { name: "notes", type: "string", required: false, description: "Observações." },
      { name: "rating", type: "number", required: false, description: "Avaliação (numérico)." },
      { name: "qualification_score", type: "number", required: false, description: "Score 0–100." },
      { name: "tier", type: "string", required: false, description: "qualification_tier: diamante|ouro|prata|bronze|desqualificado." },
      { name: "pre_qualification_tier", type: "string", required: false, description: "Mesmos valores de tier." },
      { name: "responsible_id", type: "string (uuid)", required: false, description: "Responsável (deve pertencer à org)." },
      { name: "sdr_id", type: "string (uuid)", required: false, description: "Pré-vendas." },
      { name: "closer_id", type: "string (uuid)", required: false, description: "Closer." },
    ],
    requestExample: { name: "Acme Renomeado", tier: "ouro", rating: 5 },
    responseExample: { id: "f21072f1-…", name: "Acme Renomeado", tier: "ouro", rating: 5 },
    responseFields: [{ name: "(lead 360)", type: "object", required: true, description: "Lead atualizado, mesmo shape de GET /leads/{id}." }],
    notes: [
      "422 invalid_tier para tier fora do enum. 422 invalid_responsible se o responsável não pertence à org. 422 no_valid_fields se nenhum campo editável foi enviado.",
      "Campos de negócio como segmento/faturamento/urgência são custom fields — use PUT /custom-fields.",
    ],
  },
  {
    id: "api-move-stage",
    name: "Mover etapa",
    description: "Move o lead para uma etapa de um funil. Dispara as mesmas automações da UI (workflows, meeting_events, auto-Orçamentos ao compareceu). Escopo: lead:write.",
    category: "rest-api",
    version: "v1",
    method: "POST",
    path: "/api/v1/leads/{id}/stage",
    auth,
    parameters: [
      leadIdParam,
      { name: "pipe", type: "string", required: false, description: "Funil: whatsapp, confirmacao, propostas, … Default: whatsapp.", defaultValue: "whatsapp" },
      { name: "stage", type: "string", required: true, description: "stage_key de destino (validado contra as etapas do funil)." },
    ],
    requestExample: { pipe: "confirmacao", stage: "compareceu" },
    responseExample: { moved: true, target_stage: "compareceu", target_pipe: "confirmacao" },
    responseFields: [{ name: "moved", type: "boolean", required: true, description: "Sempre true em sucesso." }],
    notes: ["400 missing_stage sem stage. 404 se o lead não for da org. 422 stage_move_failed para etapa inválida (a mensagem lista as válidas).", "meeting_date não é suportado no v1."],
  },
  {
    id: "api-add-tags",
    name: "Adicionar tags",
    description: "Adiciona tags por nome ao lead, criando as que não existem. Escopo: lead:write.",
    category: "rest-api",
    version: "v1",
    method: "POST",
    path: "/api/v1/leads/{id}/tags",
    auth,
    parameters: [
      leadIdParam,
      { name: "tags", type: "string[]", required: true, description: "Nomes de tag. Ex: [\"VIP\", \"Quente\"]." },
    ],
    requestExample: { tags: ["VIP", "Quente"] },
    responseExample: { tags: [{ id: "t1", name: "VIP", color: "#F5C518" }, { id: "t2", name: "Quente", color: "#F5C518" }] },
    responseFields: [{ name: "tags", type: "object[]", required: true, description: "Tags atuais do lead." }],
    notes: ["400 se tags não for array. 404 se o lead não for da org."],
  },
  {
    id: "api-remove-tag",
    name: "Remover tag",
    description: "Remove uma tag (por nome) do lead. Idempotente. Escopo: lead:write.",
    category: "rest-api",
    version: "v1",
    method: "DELETE",
    path: "/api/v1/leads/{id}/tags/{tag}",
    auth,
    parameters: [
      leadIdParam,
      { name: "tag", type: "string", required: true, description: "Nome da tag (path, case-insensitive)." },
    ],
    requestExample: {},
    responseExample: { removed: true },
    responseFields: [{ name: "removed", type: "boolean", required: true, description: "Sempre true." }],
    notes: ["404 se o lead não for da org."],
  },
  {
    id: "api-put-custom-fields",
    name: "Setar custom fields",
    description: "Define valores de campos customizados existentes. Não cria campos novos no v1. Escopo: lead:write.",
    category: "rest-api",
    version: "v1",
    method: "PUT",
    path: "/api/v1/leads/{id}/custom-fields",
    auth,
    parameters: [
      leadIdParam,
      { name: "<field_name>", type: "any", required: false, description: "Pares campo: valor. Ex: { \"faturamento\": \"5M\" }." },
    ],
    requestExample: { faturamento: "5M", segmento: "varejo" },
    responseExample: { updated: true },
    responseFields: [{ name: "updated", type: "boolean", required: true, description: "Sempre true em sucesso." }],
    notes: ["422 unknown_field (com details.unknown_fields) se algum campo não existe na org — nada é gravado. 404 se o lead não for da org."],
  },
];

export const restApiCategory: ApiCategory = {
  id: "rest-api",
  name: "REST API v1",
  description: "API REST pública lead-cêntrica (/api/v1/*). Leitura e escrita escopadas por API Key. Base: /functions/v1/api.",
  icon: "code",
  endpoints,
};
