import type { WizardTypeConfig } from "./types";

export const AGENDADOR_CONFIG: WizardTypeConfig = {
  type: "agendador",
  label: "Confirmador de Reuniões",
  description: "Maximiza taxa de comparecimento com confirmações inteligentes (D-5 a D-0)",
  steps: [
    "name",
    "personality",
    "businessContext",
    "conversationStyle",
    "examples",
    "availability",
    "objectiveComposite",
    "capabilities",
    "knowledgeBase",
    "customInstructions",
    "confirmationFunnel",
    "confirmerActions",
  ],
  defaults: {
    templateType: "agendador",
    operationMode: "inbound",
    attendUnknownContacts: false,
    personality: { tone: "profissional", style: "direto", energy: "moderada" },
    skills: [
      "Confirmar presença em reuniões",
      "Reagendar compromissos",
      "Enviar lembretes estratégicos",
      "Identificar risco de no-show",
      "Direcionar para próxima etapa",
    ],
    allowedTopics: [
      "Confirmação de reunião",
      "Data e horário da reunião",
      "Reagendamento",
      "Link da reunião",
      "Participantes",
      "Preparação para reunião",
      "Informações logísticas",
    ],
    forbiddenTopics: [
      "Discussões comerciais profundas",
      "Negociação de termos",
      "Qualificação detalhada",
      "Detalhes técnicos do produto",
    ],
    mainObjective:
      "Garantir o comparecimento em reuniões já agendadas através de confirmações progressivas (D-5 a D-0), reagendando quando necessário e maximizando a taxa de presença.",
    automationActions: {
      onQualify: {
        moveToStage: "compareceu",
        moveToPipe: null,
        addTags: ["confirmado"],
        notifyUserId: null,
        sendMessage: true,
        messageTemplate: "Presença confirmada! Nos vemos na reunião. Qualquer dúvida, estou por aqui.",
      },
      onDisqualify: {
        moveToStage: "remarcar",
        moveToPipe: null,
        addTags: ["reagendar"],
        notifyUserId: null,
        sendMessage: true,
        messageTemplate: "Sem problemas! Vou verificar novas opções de horário. Qual semana seria melhor para você?",
      },
      onNeedHuman: {
        moveToStage: "",
        moveToPipe: null,
        addTags: ["precisa_humano"],
        notifyUserId: null,
        sendMessage: true,
        messageTemplate: "Entendido, vou transferir para nosso time verificar pessoalmente. Um momento.",
      },
    },
    knowledgeBaseFiles: [],
    canQualifyLead: false,
    canScheduleMeeting: true,
    canSendFollowup: true,
    canUpdateCrm: false,
    canAnswerFaq: true,
    canCreateLead: false,
    canTransferHuman: true,
    canMoveCards: false,
    maxConversationTurns: 20,
    responseDelayMs: 1000,
  },
  suggestedKanbanRules: [
    {
      pipe_type: "confirmacao",
      stage_name: "reuniao_marcada",
      goal: "Enviar mensagem de boas-vindas com detalhes da reunião (data, hora, link). Confirmar recebimento.",
      behavior: "Seja caloroso e objetivo. Envie os dados da reunião de forma clara. Pergunte se o lead tem alguma dúvida.",
      allowed_actions: ["confirm_meeting", "advance_confirmation_stage", "transfer_to_human"],
      forbidden_actions: ["create_lead"],
    },
    {
      pipe_type: "confirmacao",
      stage_name: "confirmar_d5",
      goal: "Primeiro lembrete. Confirmar que a reunião continua de pé. Identificar possíveis conflitos.",
      behavior: "Abordagem leve e amigável. Pergunte se o horário ainda funciona. Se não responder, não insista nesta etapa.",
      allowed_actions: ["confirm_meeting", "advance_confirmation_stage", "transfer_to_human"],
      forbidden_actions: ["create_lead"],
    },
    {
      pipe_type: "confirmacao",
      stage_name: "confirmar_d3",
      goal: "Segundo lembrete com mais urgência. Reenviar dados da reunião. Confirmar presença.",
      behavior: "Seja direto mas cordial. Reforce o valor da reunião. Reenvie o link e horário.",
      allowed_actions: ["confirm_meeting", "advance_confirmation_stage", "schedule_meeting", "transfer_to_human"],
      forbidden_actions: ["create_lead"],
    },
    {
      pipe_type: "confirmacao",
      stage_name: "confirmar_d1",
      goal: "Confirmação final. Garantir que o lead está ciente e preparado.",
      behavior: "Tom mais urgente. Peça confirmação explícita. Se não responder, considere risco de no-show.",
      allowed_actions: ["confirm_meeting", "advance_confirmation_stage", "schedule_meeting", "transfer_to_human"],
      forbidden_actions: ["create_lead"],
    },
    {
      pipe_type: "confirmacao",
      stage_name: "confirmacao_no_dia",
      goal: "Lembrete final no dia. Enviar link novamente. Confirmar participação.",
      behavior: "Mensagem curta e direta. Envie o link da reunião. Se não responder até X minutos antes, marcar como risco.",
      allowed_actions: ["confirm_meeting", "advance_confirmation_stage", "transfer_to_human"],
      forbidden_actions: ["create_lead"],
    },
    {
      pipe_type: "confirmacao",
      stage_name: "remarcar",
      goal: "Facilitar reagendamento rápido. Oferecer novas opções de horário.",
      behavior: "Seja compreensivo. Ofereça 2-3 opções de novo horário. Confirme imediatamente. Não julgue o motivo.",
      allowed_actions: ["schedule_meeting", "advance_confirmation_stage", "transfer_to_human"],
      forbidden_actions: ["create_lead"],
    },
    {
      pipe_type: "confirmacao",
      stage_name: "perdido",
      goal: "Tentar recuperar o lead com reagendamento. Se não responder após tentativas, encerrar.",
      behavior: "Pergunte se aconteceu algo. Ofereça reagendamento. Após 2-3 tentativas sem resposta, agradeça e encerre.",
      allowed_actions: ["schedule_meeting", "advance_confirmation_stage", "transfer_to_human"],
      forbidden_actions: ["create_lead"],
    },
  ],
  suggestedCapabilities: {
    can_qualify_lead: false,
    can_schedule_meeting: true,
    can_send_followup: true,
    can_update_crm: false,
    can_answer_faq: true,
    can_create_lead: false,
    can_transfer_human: true,
  },
};
