import type { WizardTypeConfig } from "./types";

export const FOLLOWUP_CONFIG: WizardTypeConfig = {
  type: "followup",
  label: "Especialista em Follow-up",
  description: "Reengajamento estratégico de leads frios e inativos",
  steps: [
    "name",
    "personality",
    "skills",
    "businessContext",
    "conversationStyle",
    "examples",
    "availability",
    "objectiveComposite",
    "capabilities",
    "knowledgeBase",
    "customInstructions",
    "followupActions",
    "followupRules",
  ],
  defaults: {
    templateType: "followup",
    operationMode: "inbound",
    attendUnknownContacts: false,
    personality: { tone: "casual", style: "consultivo", energy: "moderada" },
    skills: [
      "Manutenção de relacionamento",
      "Reengajar leads inativos",
      "Criar urgência",
      "Identificar dor do cliente",
      "Direcionar para próxima etapa",
    ],
    allowedTopics: [
      "Status atual do lead",
      "Mudanças na empresa do lead",
      "Novas oportunidades identificadas",
      "Conteúdo relevante",
      "Check-ins periódicos",
      "Lembretes de valor",
    ],
    forbiddenTopics: [
      "Pressão excessiva para fechamento",
      "Spam de mensagens",
      "Abordagem agressiva",
      "Insistência após recusa clara",
    ],
    mainObjective:
      "Manter engajamento consistente com leads ao longo do tempo, identificando o momento ideal para reativação e avanço no funil sem ser invasivo.",
    automationActions: {
      onQualify: {
        moveToStage: "respondeu",
        moveToPipe: null,
        addTags: ["reengajado"],
        notifyUserId: null,
        sendMessage: false,
        messageTemplate: "",
      },
      onDisqualify: {
        moveToStage: "esfriou",
        moveToPipe: null,
        addTags: ["sem_resposta"],
        notifyUserId: null,
        sendMessage: true,
        messageTemplate: "Entendo que o momento pode não ser o ideal. Se algo mudar no futuro, estou por aqui! Sucesso!",
      },
      onNeedHuman: {
        moveToStage: "aguardando_humano",
        moveToPipe: null,
        addTags: ["precisa_humano"],
        notifyUserId: null,
        sendMessage: true,
        messageTemplate: "Um momento, vou transferir você para um de nossos especialistas.",
      },
    },
    knowledgeBaseFiles: [],
    canQualifyLead: false,
    canScheduleMeeting: false,
    canSendFollowup: true,
    canUpdateCrm: false,
    canAnswerFaq: true,
    canCreateLead: false,
    canTransferHuman: true,
    canMoveCards: false,
    maxConversationTurns: 20,
    responseDelayMs: 1000,
  },
  suggestedKanbanRules: [
    {
      pipe_type: "whatsapp",
      stage_name: "esfriou",
      goal: "Reengajar o lead com conteúdo de valor. Identificar se ainda há interesse.",
      behavior: "Use abordagem leve e consultiva. Ofereça algo de valor (case, novidade, conteúdo). Não pressione.",
      allowed_actions: ["update_lead"],
      forbidden_actions: ["schedule_meeting"],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "respondeu",
      goal: "Aproveitar o reengajamento para avançar no funil.",
      behavior: "Agradeça a resposta. Identifique o momento atual do lead. Direcione para próximo passo.",
      allowed_actions: ["update_lead", "schedule_meeting", "transfer_to_human"],
      forbidden_actions: [],
    },
  ],
  suggestedCapabilities: {
    can_qualify_lead: false,
    can_schedule_meeting: true,
    can_send_followup: true,
    can_update_crm: true,
    can_answer_faq: false,
    can_create_lead: false,
    can_transfer_human: true,
  },
};
