import type { WizardTypeConfig } from "./types";

export const PROSPECTADOR_CONFIG: WizardTypeConfig = {
  type: "prospectador",
  label: "Prospector Estratégico",
  description: "Mensagens personalizadas de prospecção com alto impacto",
  steps: [
    // Identidade e contexto primeiro (impacto máximo no prompt)
    "name",
    "businessContext",
    "objectiveComposite",
    // Personalidade e estilo
    "personality",
    "skills",
    "conversationStyle",
    "examples",
    "availability",
    // Configurações operacionais
    "capabilities",
    "knowledgeBase",
    "customInstructions",
    "kanbanRulesReview",
    // Específico do Prospectador
    "faqs",
    "operationMode",
    "activationTriggers",
    "outboundConfig",
    "automationActions",
    // Teste final
    "testConversation",
  ],
  defaults: {
    templateType: "prospectador",
    operationMode: "outbound",
    attendUnknownContacts: true,
    personality: { tone: "profissional", style: "persuasivo", energy: "alta" },
    skills: [
      "Fazer perguntas estratégicas",
      "Criar urgência",
      "Identificar dor do cliente",
      "Qualificar leads",
      "Direcionar para próxima etapa",
    ],
    allowedTopics: [
      "Apresentação de valor",
      "Identificação de necessidades",
      "Cases de sucesso relevantes",
      "Proposta de conversa exploratória",
      "Próximos passos",
      "Segmento da empresa",
      "Desafios comuns do mercado",
    ],
    forbiddenTopics: [
      "Mensagens genéricas",
      "Abordagem muito agressiva",
      "Promessas irrealistas",
      "Informações não verificadas",
    ],
    mainObjective:
      "Identificar e abordar novos prospectos com mensagens altamente personalizadas que geram curiosidade e engajamento inicial, abrindo portas para conversas comerciais.",
    outboundConfig: {
      delayMinutes: 3,
      firstMessageTemplate: "Oi {nome}! Sou da {empresa_propria}. Vi que vocês atuam em {segmento} e temos ajudado empresas similares com {proposta_valor}. Faz sentido trocarmos uma ideia rápida?",
      availableVariables: ["nome", "empresa", "segmento", "origem", "campanha"],
      maxRetries: 2,
      retryIntervalMinutes: 60,
    },
    knowledgeBaseFiles: [],
    canQualifyLead: true,
    canScheduleMeeting: false,
    canSendFollowup: true,
    canUpdateCrm: false,
    canAnswerFaq: true,
    canCreateLead: true,
    canTransferHuman: true,
    canMoveCards: false,
    maxConversationTurns: 20,
    responseDelayMs: 1000,
  },
  suggestedKanbanRules: [
    {
      pipe_type: "whatsapp",
      stage_name: "novo",
      goal: "Primeira abordagem personalizada. Gerar curiosidade e resposta.",
      behavior: "Mensagem curta e personalizada. Cite algo específico do lead/empresa. Termine com pergunta aberta.",
      allowed_actions: ["update_lead"],
      forbidden_actions: ["schedule_meeting"],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "abordado",
      goal: "Segunda tentativa se não houve resposta. Agregar valor.",
      behavior: "Envie conteúdo relevante (case, dado de mercado). Abordagem diferente da primeira.",
      allowed_actions: ["update_lead"],
      forbidden_actions: ["schedule_meeting"],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "respondeu",
      goal: "Converter interesse em conversa qualificada. Propor próximo passo.",
      behavior: "Identifique necessidade rapidamente. Proponha reunião ou call exploratória quando perceber fit.",
      allowed_actions: ["schedule_meeting", "update_lead", "transfer_to_human"],
      forbidden_actions: [],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "esfriou",
      goal: "Breakup message - última tentativa com abordagem diferente.",
      behavior: "Mensagem final de breakup. Ofereça valor sem pressão. Deixe porta aberta para o futuro.",
      allowed_actions: ["update_lead"],
      forbidden_actions: ["schedule_meeting"],
    },
  ],
  suggestedCapabilities: {
    can_qualify_lead: true,
    can_schedule_meeting: true,
    can_send_followup: true,
    can_update_crm: true,
    can_answer_faq: true,
    can_create_lead: true,
    can_transfer_human: true,
  },
};
