import type { WizardTypeConfig } from "./types";

export const QUALIFICADOR_CONFIG: WizardTypeConfig = {
  type: "qualificador",
  label: "Qualificador de Leads",
  description: "Qualifica leads via BANT com perguntas estratégicas",
  steps: [
    "name",
    "personality",
    "skills",
    "allowedTopics",
    "forbiddenTopics",
    "faqs",
    "businessContext",
    "conversationStyle",
    "qualification",
    "examples",
    "availability",
    "automationActions",
  ],
  defaults: {
    templateType: "qualificador",
    operationMode: "inbound",
    attendUnknownContacts: true,
    personality: { tone: "profissional", style: "consultivo", energy: "moderada" },
    skills: [
      "Identificar dor do cliente",
      "Avaliar fit produto-cliente",
      "Qualificar orçamento disponível",
      "Identificar autoridade de decisão",
      "Detectar urgência de compra",
      "Fazer perguntas estratégicas",
    ],
    allowedTopics: [
      "Desafios atuais da empresa",
      "Processos de vendas existentes",
      "Budget disponível",
      "Timeline de implementação",
      "Stakeholders envolvidos",
      "Tamanho da equipe",
      "Ferramentas atuais",
    ],
    forbiddenTopics: [
      "Preços específicos sem contexto",
      "Promessas de resultados garantidos",
      "Comparações negativas com concorrentes",
      "Informações confidenciais de outros clientes",
    ],
    mainObjective:
      "Qualificar leads através de perguntas estratégicas para identificar fit, budget, autoridade, necessidade e timeline (BANT), garantindo que apenas leads qualificados avancem no funil.",
    qualification: {
      requiredFields: [
        "Necessidade / Dor principal",
        "Orçamento disponível",
        "Autoridade de decisão",
        "Urgência / Prazo",
      ],
      optionalFields: ["Tamanho da equipe", "Ferramentas atuais"],
      notes: "",
    },
  },
  suggestedKanbanRules: [
    {
      pipe_type: "whatsapp",
      stage_name: "novo",
      goal: "Iniciar qualificação BANT: identificar necessidade e dor principal do lead",
      behavior: "Seja cordial, faça no máximo 1 pergunta por mensagem. Comece entendendo o contexto do lead.",
      allowed_actions: ["update_lead"],
      forbidden_actions: ["schedule_meeting", "transfer_to_human"],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "abordado",
      goal: "Continuar qualificação: avaliar budget e autoridade de decisão",
      behavior: "Aprofunde nas perguntas BANT. Confirme entendimento antes de avançar.",
      allowed_actions: ["update_lead"],
      forbidden_actions: ["schedule_meeting"],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "respondeu",
      goal: "Finalizar qualificação e decidir: qualificado ou desqualificado",
      behavior: "Se todos os critérios BANT foram atendidos, qualifique o lead. Caso contrário, desqualifique com cordialidade.",
      allowed_actions: ["schedule_meeting", "update_lead", "transfer_to_human"],
      forbidden_actions: [],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "esfriou",
      goal: "Tentar reengajar o lead com abordagem de valor",
      behavior: "Envie conteúdo relevante ou case de sucesso. Máximo 2 tentativas.",
      allowed_actions: ["update_lead"],
      forbidden_actions: ["schedule_meeting"],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "agendado",
      goal: "Confirmar reunião e preparar o lead",
      behavior: "Confirme data/hora, envie link se houver. Não faça novas perguntas de qualificação.",
      allowed_actions: ["schedule_meeting", "transfer_to_human"],
      forbidden_actions: [],
    },
  ],
  suggestedCapabilities: {
    can_qualify_lead: true,
    can_schedule_meeting: true,
    can_send_followup: false,
    can_update_crm: true,
    can_answer_faq: true,
    can_create_lead: false,
    can_transfer_human: true,
  },
};
