import type { WizardTypeConfig } from "./types";

export const SDR_CONFIG: WizardTypeConfig = {
  type: "sdr",
  label: "SDR - Gerador de Reuniões",
  description: "Prospecção ativa e agendamento de reuniões qualificadas",
  steps: [
    // Identidade e contexto primeiro (impacto máximo no prompt)
    "name",
    "businessContext",
    "objectiveInstructions",
    // Persona e regras (novos steps unificados)
    "personaTom",
    "rulesLimits",
    "examples",
    "knowledgeBase",
    "kanbanRulesReview",
    // Específico do SDR
    "operationMode",
    "activationTriggers",
    "outboundConfig",
    "automationActions",
    // Teste final
    "testConversation",
  ],
  defaults: {
    templateType: "sdr",
    operationMode: "hybrid",
    attendUnknownContacts: true,
    personality: { tone: "amigavel", style: "persuasivo", energy: "alta" },
    skills: [
      "Prospecção ativa",
      "Criação de rapport rápido",
      "Superação de objeções",
      "Agendar compromissos",
      "Fazer perguntas estratégicas",
      "Qualificar leads",
    ],
    allowedTopics: [
      "Apresentação da empresa",
      "Proposta de valor inicial",
      "Disponibilidade para reunião",
      "Identificação de dor",
      "Próximos passos",
      "Cases de sucesso",
    ],
    forbiddenTopics: [
      "Detalhes técnicos complexos",
      "Negociação de preços",
      "Promessas de ROI específicas",
      "Informações não verificadas",
    ],
    mainObjective:
      "Prospectar ativamente e agendar reuniões qualificadas com decisores, criando rapport rápido e superando objeções iniciais para gerar oportunidades de negócio.",
    qualification: {
      requiredFields: [
        "Necessidade / Dor principal",
        "Volume / Escopo",
        "Urgência / Prazo",
      ],
      optionalFields: ["Orçamento disponível", "Ferramentas atuais"],
      notes: "",
    },
    outboundConfig: {
      delayMinutes: 5,
      firstMessageTemplate: "Oi {nome}! 👋 Vi que você demonstrou interesse em {interesse}. O que mais te chamou atenção?",
      availableVariables: ["nome", "empresa", "email", "telefone", "origem", "interesse", "segmento", "campanha"],
      maxRetries: 3,
      retryIntervalMinutes: 30,
      audioEnabled: false,
      audioSendOrder: "text_first" as const,
    },
    knowledgeBaseFiles: [],
    canQualifyLead: true,
    canScheduleMeeting: true,
    canSendFollowup: true,
    canUpdateCrm: false,
    canAnswerFaq: true,
    canCreateLead: true,
    canTransferHuman: true,
    canMoveCards: false,
    maxConversationTurns: 20,
    responseDelayMs: 1000,
  },
  suggestedKanbanRules: [
    {
      pipe_type: "whatsapp",
      stage_name: "novo",
      goal: "Criar rapport e gerar interesse inicial. Apresentar proposta de valor de forma concisa.",
      behavior: "Seja amigável e direto. Faça 1 pergunta por mensagem. Mostre que pesquisou sobre o lead.",
      allowed_actions: ["update_lead"],
      forbidden_actions: ["schedule_meeting"],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "abordado",
      goal: "Aprofundar interesse e identificar dor. Superar objeções iniciais.",
      behavior: "Use técnicas SPIN. Compartilhe cases relevantes. Direcione para reunião quando perceber fit.",
      allowed_actions: ["update_lead", "schedule_meeting"],
      forbidden_actions: [],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "respondeu",
      goal: "Converter em reunião agendada. Fechar próximo passo concreto.",
      behavior: "Proponha horários específicos. Supere objeções de agenda. Gere urgência sem pressionar.",
      allowed_actions: ["schedule_meeting", "update_lead", "transfer_to_human"],
      forbidden_actions: [],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "esfriou",
      goal: "Reengajar com nova abordagem de valor. Última tentativa antes de descartar.",
      behavior: "Envie conteúdo novo (case, artigo, novidade). Máximo 2 tentativas de reengajamento.",
      allowed_actions: ["update_lead"],
      forbidden_actions: ["schedule_meeting"],
    },
    {
      pipe_type: "whatsapp",
      stage_name: "agendado",
      goal: "Garantir comparecimento na reunião. Preparar lead para a conversa.",
      behavior: "Confirme detalhes da reunião. Envie material preparatório se necessário.",
      allowed_actions: ["schedule_meeting", "transfer_to_human"],
      forbidden_actions: [],
    },
  ],
  suggestedCapabilities: {
    can_qualify_lead: true,
    can_schedule_meeting: true,
    can_send_followup: true,
    can_update_crm: true,
    can_answer_faq: true,
    can_create_lead: true,
    can_transfer_human: true,
  },
};
