-- Generated by CLI as 20260921141339; ordered after the existing future chain
-- before any apply. No activation, catalog seed, ERP call or data backfill.
-- Only new, explicitly owned preorders participate in the identity guard.
BEGIN;

CREATE TABLE public.toth_preorder_operations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id),
  deal_id uuid NOT NULL REFERENCES public.deals(id),
  draft_id uuid NOT NULL,
  draft_revision integer NOT NULL CHECK (draft_revision>0),
  lead_id uuid NOT NULL REFERENCES public.leads(id),
  client_id uuid NOT NULL REFERENCES public.upsell_clients(id),
  requested_by uuid NOT NULL REFERENCES auth.users(id),
  request_snapshot jsonb NOT NULL CHECK (jsonb_typeof(request_snapshot)='object'),
  delivery_state text NOT NULL DEFAULT 'queued' CHECK (delivery_state IN ('queued','sending','awaiting_confirmation','received','failed','blocked')),
  commercial_state text NOT NULL DEFAULT 'unknown' CHECK (commercial_state IN ('pending','approved','rejected','unknown')),
  reconciliation_state text NOT NULL DEFAULT 'not_due' CHECK (reconciliation_state IN ('not_due','pending','complete','blocked')),
  external_id text CHECK (length(external_id) BETWEEN 1 AND 128 AND btrim(external_id)=external_id AND external_id !~ '[[:cntrl:]]'),
  approved_total numeric CHECK (approved_total>0 AND approved_total<=9999999999.99 AND round(approved_total,2)=approved_total),
  source_marker text,
  source_order bigint CHECK (source_order BETWEEN 0 AND 9007199254740991),
  observation_source text CHECK (observation_source IN ('authoritative_lookup','authoritative_create')),
  lease_token uuid,
  lease_expires_at timestamptz,
  attempts integer NOT NULL DEFAULT 0,
  local_sale_event_id uuid REFERENCES public.sale_events(id),
  last_error_code text CHECK (last_error_code ~ '^[a-z][a-z0-9_]{0,99}$'),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(organization_id,id),
  UNIQUE(organization_id,deal_id),
  FOREIGN KEY(organization_id,draft_id) REFERENCES public.toth_order_drafts(organization_id,id),
  CHECK (organization_id='4922638c-4909-494e-ba10-12282ec0b161'::uuid),
  CHECK ((lease_token IS NULL)=(lease_expires_at IS NULL)),
  CHECK (commercial_state<>'approved' OR (approved_total IS NOT NULL AND observation_source='authoritative_lookup')),
  CHECK (reconciliation_state<>'complete' OR local_sale_event_id IS NOT NULL)
);
CREATE UNIQUE INDEX toth_preorder_external_identity ON public.toth_preorder_operations(organization_id,external_id) WHERE external_id IS NOT NULL;
CREATE INDEX toth_preorder_draft_idx ON public.toth_preorder_operations(draft_id);
CREATE INDEX toth_preorder_client_idx ON public.toth_preorder_operations(client_id);
CREATE INDEX toth_preorder_lead_idx ON public.toth_preorder_operations(lead_id);
CREATE TABLE public.toth_preorder_audit (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id),
  operation_id uuid NOT NULL,
  action text NOT NULL,
  state jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(organization_id,operation_id) REFERENCES public.toth_preorder_operations(organization_id,id)
);
CREATE INDEX toth_preorder_audit_operation_idx ON public.toth_preorder_audit(organization_id,operation_id,created_at);

-- Sealed until a reviewed supplier contract, isolated homologation, commercial
-- validation and deployment are proven. Neither a browser flag nor service
-- configuration can make this true. Tests replace it only in their local DB.
CREATE FUNCTION toth_order_private.preorder_runtime_ready() RETURNS boolean
LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT false $$;

CREATE FUNCTION toth_order_private.preorder_item(p_id uuid) RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
  SELECT to_jsonb(o) FROM public.toth_preorder_operations o
  WHERE o.id=p_id AND o.organization_id='4922638c-4909-494e-ba10-12282ec0b161'::uuid;
$$;
CREATE FUNCTION toth_order_private.preorder_audit(p_id uuid,p_action text) RETURNS void
LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$
  INSERT INTO public.toth_preorder_audit(organization_id,operation_id,action,state)
    SELECT organization_id,id,p_action,jsonb_build_object('delivery_state',delivery_state,'commercial_state',commercial_state,
      'reconciliation_state',reconciliation_state,'external_id',external_id,'source_marker',source_marker,
      'source_order',source_order,'approved_total',approved_total,'local_sale_event_id',local_sale_event_id,
      'last_error_code',last_error_code,'requested_by',requested_by)
    FROM public.toth_preorder_operations WHERE id=p_id AND organization_id='4922638c-4909-494e-ba10-12282ec0b161'::uuid;
$$;
CREATE FUNCTION toth_order_private.preorder_lease(p_id uuid,p_token uuid) RETURNS public.toth_preorder_operations
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_op public.toth_preorder_operations%ROWTYPE;
BEGIN
  SELECT * INTO v_op FROM public.toth_preorder_operations
    WHERE id=p_id AND organization_id='4922638c-4909-494e-ba10-12282ec0b161'::uuid FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'toth_operation_unavailable' USING ERRCODE='P0002'; END IF;
  IF p_token IS NULL OR v_op.lease_token IS DISTINCT FROM p_token OR v_op.lease_expires_at<=clock_timestamp() THEN
    RAISE EXCEPTION 'toth_lease_lost' USING ERRCODE='40001';
  END IF;
  RETURN v_op;
END;
$$;
CREATE FUNCTION toth_order_private.preorder_block(p_id uuid,p_error text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
  IF p_error IS NULL OR p_error !~ '^[a-z][a-z0-9_]{0,99}$' THEN RAISE EXCEPTION 'toth_invalid_error_code'; END IF;
  UPDATE public.toth_preorder_operations SET delivery_state=CASE WHEN external_id IS NULL THEN 'blocked' ELSE delivery_state END,
    reconciliation_state='blocked',last_error_code=p_error,updated_at=clock_timestamp()
    WHERE id=p_id AND organization_id='4922638c-4909-494e-ba10-12282ec0b161'::uuid;
  PERFORM toth_order_private.preorder_audit(p_id,'blocked');
  RETURN toth_order_private.preorder_item(p_id);
END;
$$;
CREATE FUNCTION public.toth_preorder_can_read(p_id uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
  SELECT EXISTS (SELECT 1 FROM public.toth_preorder_operations o JOIN public.deals d
    ON d.id=o.deal_id AND d.organization_id=o.organization_id AND d.source_lead_id=o.lead_id AND d.deleted_at IS NULL
    WHERE o.id=p_id AND o.organization_id='4922638c-4909-494e-ba10-12282ec0b161'::uuid AND public.toth_order_can_read(o.deal_id));
$$;
ALTER TABLE public.toth_preorder_operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.toth_preorder_audit ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_select ON public.toth_preorder_operations FOR SELECT TO authenticated
  USING(organization_id IN (SELECT public.get_my_organization_ids()) AND public.toth_preorder_can_read(id));
CREATE POLICY tenant_isolation_select ON public.toth_preorder_audit FOR SELECT TO authenticated
  USING(organization_id IN (SELECT public.get_my_organization_ids()) AND public.toth_preorder_can_read(operation_id));
REVOKE ALL ON public.toth_preorder_operations,public.toth_preorder_audit FROM PUBLIC,anon,authenticated,service_role;
-- Browser gets only state via the workspace RPC: never immutable request or lease.

CREATE FUNCTION toth_order_private.preorder_immutable_origin() RETURNS trigger
LANGUAGE plpgsql SET search_path='' AS $$
BEGIN
  IF (NEW.id,NEW.organization_id,NEW.deal_id,NEW.draft_id,NEW.draft_revision,NEW.lead_id,NEW.client_id,NEW.requested_by,NEW.request_snapshot,NEW.created_at)
    IS DISTINCT FROM (OLD.id,OLD.organization_id,OLD.deal_id,OLD.draft_id,OLD.draft_revision,OLD.lead_id,OLD.client_id,OLD.requested_by,OLD.request_snapshot,OLD.created_at)
    OR (OLD.external_id IS NOT NULL AND NEW.external_id IS DISTINCT FROM OLD.external_id) THEN
    RAISE EXCEPTION 'toth_operation_origin_immutable' USING ERRCODE='42501';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER toth_preorder_origin_immutable BEFORE UPDATE ON public.toth_preorder_operations
  FOR EACH ROW EXECUTE FUNCTION toth_order_private.preorder_immutable_origin();
CREATE FUNCTION toth_order_private.preorder_freeze_draft() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
  IF EXISTS(SELECT 1 FROM public.toth_preorder_operations o WHERE o.organization_id=OLD.organization_id AND o.draft_id=OLD.id) THEN
    RAISE EXCEPTION 'toth_draft_already_submitted' USING ERRCODE='42501';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER toth_preorder_freeze_draft BEFORE UPDATE ON public.toth_order_drafts
  FOR EACH ROW EXECUTE FUNCTION toth_order_private.preorder_freeze_draft();

-- Closing an owned deal manually, through a stage or through a workflow must
-- obey the same approval boundary. Read without another row lock: canonical
-- reconciliation already locks operation -> deal, while UI holds the deal.
CREATE FUNCTION public.toth_preorder_gain_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_op public.toth_preorder_operations%ROWTYPE;
BEGIN
  IF OLD.outcome IS NOT DISTINCT FROM NEW.outcome AND OLD.value IS NOT DISTINCT FROM NEW.value THEN RETURN NEW; END IF;
  SELECT * INTO v_op FROM public.toth_preorder_operations WHERE deal_id=OLD.id AND organization_id=OLD.organization_id;
  IF NOT FOUND THEN RETURN NEW; END IF;
  -- This phase recognizes the first approved order only. Local changes to an
  -- already recognized order need a future ERP adjustment/reversal contract;
  -- never let the generic won-order editor rewrite its amount or reopen it.
  IF OLD.outcome='won' AND v_op.commercial_state='approved'
    AND (NEW.outcome IS DISTINCT FROM 'won' OR NEW.value IS DISTINCT FROM OLD.value) THEN
    RAISE EXCEPTION 'toth_owned_order_manual_change_blocked' USING ERRCODE='55000';
  END IF;
  IF OLD.outcome IS NOT DISTINCT FROM NEW.outcome OR NEW.outcome<>'won' THEN RETURN NEW; END IF;
  IF v_op.delivery_state<>'received' OR v_op.commercial_state<>'approved'
    OR v_op.observation_source<>'authoritative_lookup' OR v_op.reconciliation_state='blocked'
    OR NEW.organization_id IS DISTINCT FROM v_op.organization_id OR NEW.source_lead_id IS DISTINCT FROM v_op.lead_id
    OR NEW.currency IS DISTINCT FROM 'BRL' OR NEW.value IS DISTINCT FROM v_op.approved_total THEN
    RAISE EXCEPTION 'toth_approval_required_for_gain' USING ERRCODE='55000';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER toth_preorder_gain_guard BEFORE UPDATE OF outcome,value ON public.deals
  FOR EACH ROW EXECUTE FUNCTION public.toth_preorder_gain_guard();

-- The generic adjustment RPC can change composition without changing the total.
-- Its final audit insert is in the same transaction, so rejection here also
-- rolls back preceding item, deal, ledger and Carteira changes. A true no-op
-- never inserts an adjustment. Unowned historical orders keep their behavior.
CREATE FUNCTION toth_order_private.preorder_adjustment_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
  IF EXISTS(SELECT 1 FROM public.toth_preorder_operations o
    WHERE o.organization_id=NEW.organization_id AND o.deal_id=NEW.deal_id AND o.commercial_state='approved') THEN
    RAISE EXCEPTION 'toth_owned_order_manual_change_blocked' USING ERRCODE='55000';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER toth_preorder_adjustment_guard BEFORE INSERT ON public.deal_order_adjustments
  FOR EACH ROW EXECUTE FUNCTION toth_order_private.preorder_adjustment_guard();

-- Guard the canonical ledger as well: its currency comes from pipeline metadata,
-- and some legacy reversal writers do not update the deal outcome first.
-- These guards read the owned operation without a row lock (deal -> operation
-- would invert the worker's operation -> deal locking order).
CREATE FUNCTION toth_order_private.preorder_sale_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_op public.toth_preorder_operations%ROWTYPE;
BEGIN
  IF NEW.event_type='sale_reversed' AND EXISTS(
    SELECT 1 FROM public.sale_events s JOIN public.toth_preorder_operations o
      ON o.deal_id=s.deal_id AND o.organization_id=s.organization_id
    WHERE s.id=NEW.reversed_event_id AND o.commercial_state='approved') THEN
    RAISE EXCEPTION 'toth_owned_order_manual_change_blocked' USING ERRCODE='55000';
  END IF;
  IF NEW.event_type<>'sale' OR NEW.deal_id IS NULL THEN RETURN NEW; END IF;
  SELECT * INTO v_op FROM public.toth_preorder_operations WHERE deal_id=NEW.deal_id AND organization_id=NEW.organization_id;
  IF NOT FOUND THEN RETURN NEW; END IF;
  IF v_op.delivery_state<>'received' OR v_op.commercial_state<>'approved'
    OR v_op.observation_source<>'authoritative_lookup' OR v_op.reconciliation_state='blocked'
    OR NEW.lead_id IS DISTINCT FROM v_op.lead_id OR NEW.currency IS DISTINCT FROM 'BRL'
    OR NEW.sale_value IS DISTINCT FROM v_op.approved_total OR NEW.producer NOT IN('funnel','deal')
    OR NEW.origin_record_id IS NOT NULL THEN
    RAISE EXCEPTION 'toth_approval_required_for_gain' USING ERRCODE='55000';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER toth_preorder_sale_guard BEFORE INSERT ON public.sale_events
  FOR EACH ROW EXECUTE FUNCTION toth_order_private.preorder_sale_guard();

-- Shared identity lock with remote-result binding. Unowned historical ERP rows
-- retain the exact old behavior. Owned IDs must use the new observation path;
-- the generic importer must never create a second Carteira order or sale.
CREATE FUNCTION toth_order_private.preorder_identity_lock(p_org uuid,p_external_id text) RETURNS void
LANGUAGE sql SET search_path='' AS $$
  SELECT pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('toth-preorder:'||p_org::text||':'||p_external_id,0));
$$;
CREATE FUNCTION public.toth_preorder_legacy_import_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
  IF NEW.organization_id='4922638c-4909-494e-ba10-12282ec0b161'::uuid AND NEW.external_source='toth' AND NEW.external_id IS NOT NULL THEN
    PERFORM toth_order_private.preorder_identity_lock(NEW.organization_id,NEW.external_id);
    IF EXISTS(SELECT 1 FROM public.toth_preorder_operations o WHERE o.organization_id=NEW.organization_id AND o.external_id=NEW.external_id) THEN
      RAISE EXCEPTION 'toth_preorder_owned_external_id' USING ERRCODE='23505';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER toth_preorder_legacy_import_guard BEFORE INSERT OR UPDATE ON public.upsell_orders
  FOR EACH ROW EXECUTE FUNCTION public.toth_preorder_legacy_import_guard();
CREATE FUNCTION public.toth_find_owned_preorder(p_organization_id uuid,p_external_id text) RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
  SELECT jsonb_build_object('id',id,'organization_id',organization_id,'deal_id',deal_id,'external_id',external_id)
  FROM public.toth_preorder_operations WHERE organization_id=p_organization_id
    AND organization_id='4922638c-4909-494e-ba10-12282ec0b161'::uuid AND external_id=p_external_id;
$$;

CREATE FUNCTION public.toth_preorder_workspace(p_deal_id uuid) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_base jsonb; v_op public.toth_preorder_operations%ROWTYPE; v_blockers jsonb:='[]'; v_can boolean;
BEGIN
  v_base:=public.toth_order_workspace(p_deal_id);
  IF NOT toth_order_private.preorder_runtime_ready() THEN
    v_blockers:='["supplier_contract_unverified","homologation_unverified","commercial_validation_unavailable","writes_disabled"]';
  END IF;
  IF NOT (v_base->>'enabled')::boolean THEN v_blockers:=v_blockers||'["drafts_disabled"]'; END IF;
  IF NOT (v_base->>'can_review')::boolean THEN v_blockers:=v_blockers||'["admin_required"]'; END IF;
  IF v_base->'draft' IS NULL OR v_base->'draft'='null'::jsonb THEN v_blockers:=v_blockers||'["draft_required"]';
  ELSIF v_base#>>'{draft,reviewed_revision}' IS DISTINCT FROM v_base#>>'{draft,revision}'
    OR v_base#>>'{draft,reviewed_by}' IS NULL THEN v_blockers:=v_blockers||'["current_review_required"]'; END IF;
  IF v_base->'draft' IS NOT NULL AND v_base->'draft'<>'null'::jsonb THEN
    BEGIN
      PERFORM toth_order_private.validate_items('4922638c-4909-494e-ba10-12282ec0b161'::uuid,v_base#>'{draft,items}');
    EXCEPTION WHEN OTHERS THEN v_blockers:=v_blockers||'["catalog_item_unavailable"]'; END;
  END IF;
  SELECT * INTO v_op FROM public.toth_preorder_operations WHERE deal_id=p_deal_id
    AND organization_id='4922638c-4909-494e-ba10-12282ec0b161'::uuid;
  IF FOUND AND NOT public.toth_preorder_can_read(v_op.id) THEN
    RETURN jsonb_build_object('can_send',false,'operation',NULL,'blockers',v_blockers||'["client_link_changed"]');
  END IF;
  IF v_op.id IS NOT NULL THEN v_blockers:=v_blockers||'["operation_already_created"]'; END IF;
  v_can:=jsonb_array_length(v_blockers)=0;
  RETURN jsonb_build_object('can_send',v_can,'blockers',v_blockers,'operation',CASE WHEN v_op.id IS NULL THEN NULL ELSE
    jsonb_build_object('id',v_op.id,'draft_revision',v_op.draft_revision,'delivery_state',v_op.delivery_state,
      'commercial_state',v_op.commercial_state,'reconciliation_state',v_op.reconciliation_state,'external_id',v_op.external_id,
      'approved_total',v_op.approved_total,'updated_at',v_op.updated_at,'last_error_code',v_op.last_error_code) END);
END;
$$;
CREATE OR REPLACE FUNCTION public.toth_request_order_send(p_deal_id uuid,p_expected_revision integer) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_ctx jsonb; v_draft public.toth_order_drafts%ROWTYPE; v_customer jsonb; v_id uuid; v_deal public.deals%ROWTYPE;
BEGIN
  v_ctx:=toth_order_private.context(p_deal_id,true);
  IF NOT (v_ctx->>'enabled')::boolean THEN RAISE EXCEPTION 'toth_drafts_disabled' USING ERRCODE='42501'; END IF;
  IF NOT (v_ctx->>'can_review')::boolean THEN RAISE EXCEPTION 'toth_access_denied' USING ERRCODE='42501'; END IF;
  IF NOT toth_order_private.preorder_runtime_ready() THEN RAISE EXCEPTION 'toth_write_contract_unverified' USING ERRCODE='55000'; END IF;
  SELECT * INTO v_draft FROM public.toth_order_drafts WHERE deal_id=p_deal_id AND organization_id=(v_ctx->>'organization_id')::uuid FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'toth_draft_unavailable' USING ERRCODE='P0002'; END IF;
  IF p_expected_revision IS NULL OR v_draft.revision IS DISTINCT FROM p_expected_revision THEN RAISE EXCEPTION 'toth_revision_conflict' USING ERRCODE='40001'; END IF;
  SELECT id INTO v_id FROM public.toth_preorder_operations WHERE organization_id=v_draft.organization_id AND deal_id=p_deal_id;
  IF FOUND THEN RETURN public.toth_preorder_workspace(p_deal_id); END IF;
  IF v_draft.reviewed_revision IS DISTINCT FROM v_draft.revision OR v_draft.reviewed_by IS NULL
    OR jsonb_array_length(v_draft.items)=0 THEN RAISE EXCEPTION 'toth_current_review_required' USING ERRCODE='22023'; END IF;
  v_customer:=toth_order_private.customer(v_draft.organization_id,(v_ctx->>'lead_id')::uuid);
  IF v_customer IS NULL OR v_draft.lead_id IS DISTINCT FROM (v_ctx->>'lead_id')::uuid
    OR v_draft.client_id IS DISTINCT FROM (v_customer->>'client_id')::uuid
    OR v_draft.customer_external_id IS DISTINCT FROM v_customer->>'customer_external_id' THEN
    RAISE EXCEPTION 'toth_client_link_changed' USING ERRCODE='40001';
  END IF;
  PERFORM toth_order_private.validate_items(v_draft.organization_id,v_draft.items);
  SELECT * INTO v_deal FROM public.deals WHERE id=p_deal_id AND organization_id=v_draft.organization_id;
  IF v_deal.outcome NOT IN ('open','won') OR v_deal.currency IS DISTINCT FROM 'BRL' OR v_deal.value<0 THEN RAISE EXCEPTION 'toth_deal_not_eligible' USING ERRCODE='22023'; END IF;
  INSERT INTO public.toth_preorder_operations(organization_id,deal_id,draft_id,draft_revision,lead_id,client_id,requested_by,request_snapshot)
    VALUES(v_draft.organization_id,p_deal_id,v_draft.id,v_draft.revision,v_draft.lead_id,v_draft.client_id,auth.uid(),
      jsonb_build_object('schema_version',1,'id',v_draft.id,'deal_id',p_deal_id,'revision',v_draft.revision,
        'lead_id',v_draft.lead_id,'client_id',v_draft.client_id,'customer_external_id',v_draft.customer_external_id,'items',v_draft.items,'notes',v_draft.notes,
        'deal_outcome',v_deal.outcome,'deal_value',v_deal.value,'currency',v_deal.currency)) RETURNING id INTO v_id;
  PERFORM toth_order_private.preorder_audit(v_id,'queued');
  RETURN public.toth_preorder_workspace(p_deal_id);
END;
$$;

CREATE FUNCTION public.toth_claim_preorder_operation(p_operation_id uuid) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_op public.toth_preorder_operations%ROWTYPE;
BEGIN
  SELECT * INTO v_op FROM public.toth_preorder_operations WHERE id=p_operation_id
    AND organization_id='4922638c-4909-494e-ba10-12282ec0b161'::uuid FOR UPDATE;
  IF NOT FOUND THEN RETURN NULL; END IF;
  IF v_op.lease_expires_at>clock_timestamp() OR (v_op.delivery_state IN ('failed','blocked') AND v_op.external_id IS NULL) THEN RETURN NULL; END IF;
  UPDATE public.toth_preorder_operations SET lease_token=gen_random_uuid(),lease_expires_at=clock_timestamp()+interval '120 seconds',
    attempts=attempts+1,updated_at=clock_timestamp() WHERE id=v_op.id AND organization_id=v_op.organization_id;
  -- Expired 'sending' is deliberately NOT reset to queued: lookup only.
  PERFORM toth_order_private.preorder_audit(v_op.id,'claimed');
  RETURN toth_order_private.preorder_item(v_op.id);
END;
$$;
CREATE FUNCTION public.toth_mark_preorder_sending(p_operation_id uuid,p_lease_token uuid) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_op public.toth_preorder_operations%ROWTYPE; v_customer jsonb; v_deal public.deals%ROWTYPE;
BEGIN
  v_op:=toth_order_private.preorder_lease(p_operation_id,p_lease_token);
  IF v_op.delivery_state<>'queued' THEN RAISE EXCEPTION 'toth_operation_already_dispatched' USING ERRCODE='40001'; END IF;
  IF NOT toth_order_private.preorder_runtime_ready() THEN RETURN toth_order_private.preorder_block(v_op.id,'toth_write_contract_unverified'); END IF;
  IF NOT toth_order_private.enabled(v_op.organization_id) OR NOT EXISTS(SELECT 1 FROM public.team_members m
    WHERE m.organization_id=v_op.organization_id AND m.user_id=v_op.requested_by AND m.is_active AND m.role='admin')
    OR NOT EXISTS(SELECT 1 FROM public.deals d JOIN public.leads l ON l.id=d.source_lead_id AND l.organization_id=d.organization_id AND l.deleted_at IS NULL
      WHERE d.id=v_op.deal_id AND d.organization_id=v_op.organization_id AND d.source_lead_id=v_op.lead_id AND d.deleted_at IS NULL) THEN
    RETURN toth_order_private.preorder_block(v_op.id,'toth_sender_access_revoked');
  END IF;
  SELECT * INTO v_deal FROM public.deals WHERE id=v_op.deal_id AND organization_id=v_op.organization_id FOR UPDATE;
  IF NOT FOUND OR v_deal.deleted_at IS NOT NULL OR v_deal.source_lead_id IS DISTINCT FROM v_op.lead_id
    OR v_deal.outcome IS DISTINCT FROM v_op.request_snapshot->>'deal_outcome'
    OR v_deal.currency IS DISTINCT FROM 'BRL' OR v_deal.value IS DISTINCT FROM (v_op.request_snapshot->>'deal_value')::numeric THEN
    RETURN toth_order_private.preorder_block(v_op.id,'toth_deal_changed');
  END IF;
  v_customer:=toth_order_private.customer(v_op.organization_id,v_op.lead_id);
  IF v_customer IS NULL OR (v_customer->>'client_id')::uuid IS DISTINCT FROM v_op.client_id
    OR v_customer->>'customer_external_id' IS DISTINCT FROM v_op.request_snapshot->>'customer_external_id' THEN
    RETURN toth_order_private.preorder_block(v_op.id,'toth_client_link_changed');
  END IF;
  BEGIN
    PERFORM toth_order_private.validate_items(v_op.organization_id,v_op.request_snapshot->'items');
  EXCEPTION WHEN OTHERS THEN RETURN toth_order_private.preorder_block(v_op.id,'toth_catalog_item_unavailable'); END;
  UPDATE public.toth_preorder_operations SET delivery_state='sending',updated_at=clock_timestamp()
    WHERE id=v_op.id AND organization_id=v_op.organization_id;
  PERFORM toth_order_private.preorder_audit(v_op.id,'sending');
  RETURN toth_order_private.preorder_item(v_op.id);
END;
$$;
CREATE FUNCTION public.toth_mark_preorder_uncertain(p_operation_id uuid,p_lease_token uuid,p_error_code text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_op public.toth_preorder_operations%ROWTYPE;
BEGIN
  v_op:=toth_order_private.preorder_lease(p_operation_id,p_lease_token);
  IF p_error_code IS NULL OR p_error_code !~ '^[a-z][a-z0-9_]{0,99}$' THEN RAISE EXCEPTION 'toth_invalid_error_code'; END IF;
  IF v_op.delivery_state NOT IN ('sending','awaiting_confirmation','received') THEN RAISE EXCEPTION 'toth_invalid_delivery_transition'; END IF;
  UPDATE public.toth_preorder_operations SET delivery_state=CASE WHEN delivery_state='received' THEN 'received' ELSE 'awaiting_confirmation' END,
    last_error_code=p_error_code,updated_at=clock_timestamp() WHERE id=v_op.id AND organization_id=v_op.organization_id;
  PERFORM toth_order_private.preorder_audit(v_op.id,'uncertain');
  RETURN toth_order_private.preorder_item(v_op.id);
END;
$$;
CREATE FUNCTION public.toth_block_preorder_operation(p_operation_id uuid,p_lease_token uuid,p_error_code text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
  PERFORM toth_order_private.preorder_lease(p_operation_id,p_lease_token);
  RETURN toth_order_private.preorder_block(p_operation_id,p_error_code);
END;
$$;

CREATE FUNCTION public.toth_record_preorder_observation(p_operation_id uuid,p_lease_token uuid,p_observation jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_op public.toth_preorder_operations%ROWTYPE; v_external text; v_status text; v_source text; v_marker text; v_order bigint; v_total numeric;
BEGIN
  v_op:=toth_order_private.preorder_lease(p_operation_id,p_lease_token);
  IF jsonb_typeof(p_observation) IS DISTINCT FROM 'object' OR p_observation->>'operation_id' IS DISTINCT FROM v_op.id::text
    OR NOT(p_observation ?& ARRAY['external_id','status','source','source_marker','source_order','approved_total'])
    OR p_observation-ARRAY['operation_id','external_id','status','source','source_marker','source_order','approved_total']<>'{}'::jsonb
    OR jsonb_typeof(p_observation->'operation_id') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_observation->'external_id') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_observation->'status') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_observation->'source') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_observation->'source_marker') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_observation->'source_order') IS DISTINCT FROM 'number' THEN RAISE EXCEPTION 'toth_invalid_observation' USING ERRCODE='22023'; END IF;
  v_external:=p_observation->>'external_id'; v_status:=p_observation->>'status'; v_source:=p_observation->>'source'; v_marker:=p_observation->>'source_marker';
  IF v_external IS NULL OR length(v_external) NOT BETWEEN 1 AND 128 OR btrim(v_external)<>v_external OR v_external~'[[:cntrl:]]'
    OR v_status IS NULL OR v_status NOT IN ('pending','approved','rejected','unknown') OR v_source IS NULL OR v_source NOT IN ('authoritative_lookup','authoritative_create')
    OR (v_source='authoritative_create' AND v_status='rejected')
    OR v_marker IS NULL OR length(v_marker) NOT BETWEEN 1 AND 256 OR btrim(v_marker)<>v_marker OR v_marker~'[[:cntrl:]]'
    OR (p_observation->>'source_order')::numeric NOT BETWEEN 0 AND 9007199254740991
    OR trunc((p_observation->>'source_order')::numeric)<>(p_observation->>'source_order')::numeric THEN RAISE EXCEPTION 'toth_invalid_observation' USING ERRCODE='22023'; END IF;
  v_order:=(p_observation->>'source_order')::bigint;
  IF v_status='approved' THEN
    IF v_source<>'authoritative_lookup' OR jsonb_typeof(p_observation->'approved_total') IS DISTINCT FROM 'number' THEN
      RAISE EXCEPTION 'toth_approval_requires_authoritative_lookup' USING ERRCODE='22023'; END IF;
    v_total:=(p_observation->>'approved_total')::numeric;
    IF v_total<=0 OR v_total>9999999999.99 OR round(v_total,2)<>v_total THEN RAISE EXCEPTION 'toth_invalid_approved_total' USING ERRCODE='22023'; END IF;
  ELSIF p_observation->'approved_total' IS DISTINCT FROM 'null'::jsonb THEN RAISE EXCEPTION 'toth_invalid_approved_total' USING ERRCODE='22023'; END IF;
  IF v_op.delivery_state NOT IN ('sending','awaiting_confirmation','received') THEN RAISE EXCEPTION 'toth_invalid_delivery_transition'; END IF;
  IF v_op.external_id IS NOT NULL AND v_op.external_id<>v_external THEN RETURN toth_order_private.preorder_block(v_op.id,'toth_external_identity_changed'); END IF;
  IF v_op.source_order IS NOT NULL AND v_order<v_op.source_order THEN RETURN toth_order_private.preorder_item(v_op.id); END IF;
  IF v_op.source_order=v_order THEN
    IF v_op.source_marker=v_marker AND v_op.commercial_state=v_status AND v_op.approved_total IS NOT DISTINCT FROM v_total THEN
      RETURN toth_order_private.preorder_item(v_op.id);
    END IF;
    RETURN toth_order_private.preorder_block(v_op.id,'toth_observation_version_conflict');
  END IF;
  -- Unknown is never allowed to erase an existing confirmed business state.
  IF v_status='unknown' AND v_op.commercial_state<>'unknown' THEN RETURN toth_order_private.preorder_block(v_op.id,'toth_unknown_commercial_status'); END IF;
  IF v_op.commercial_state='approved' AND (v_status<>'approved' OR v_total IS DISTINCT FROM v_op.approved_total) THEN
    RETURN toth_order_private.preorder_block(v_op.id,'toth_approved_order_changed');
  END IF;
  IF v_op.commercial_state='rejected' AND v_status<>'rejected' THEN RETURN toth_order_private.preorder_block(v_op.id,'toth_rejected_order_changed'); END IF;
  PERFORM toth_order_private.preorder_identity_lock(v_op.organization_id,v_external);
  IF EXISTS(SELECT 1 FROM public.toth_preorder_operations o WHERE o.organization_id=v_op.organization_id AND o.external_id=v_external AND o.id<>v_op.id) THEN
    RETURN toth_order_private.preorder_block(v_op.id,'toth_external_identity_owned');
  END IF;
  IF EXISTS(SELECT 1 FROM public.upsell_orders u WHERE u.organization_id=v_op.organization_id AND u.external_source='toth' AND u.external_id=v_external) THEN
    -- Do not bind: the guard must not freeze or rewrite this historical order.
    RETURN toth_order_private.preorder_block(v_op.id,'toth_existing_erp_order_conflict');
  END IF;
  UPDATE public.toth_preorder_operations SET external_id=v_external,delivery_state='received',commercial_state=v_status,
    approved_total=v_total,source_marker=v_marker,source_order=v_order,observation_source=v_source,
    reconciliation_state=CASE WHEN reconciliation_state IN ('complete','blocked') THEN reconciliation_state WHEN v_status='approved' THEN 'pending' ELSE 'not_due' END,
    last_error_code=CASE WHEN reconciliation_state='blocked' THEN last_error_code ELSE NULL END,updated_at=clock_timestamp()
    WHERE id=v_op.id AND organization_id=v_op.organization_id;
  PERFORM toth_order_private.preorder_audit(v_op.id,'observation_recorded');
  RETURN toth_order_private.preorder_item(v_op.id);
END;
$$;

CREATE FUNCTION public.toth_reconcile_preorder_operation(p_operation_id uuid,p_lease_token uuid) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_op public.toth_preorder_operations%ROWTYPE; v_deal public.deals%ROWTYPE; v_count integer; v_sale public.sale_events%ROWTYPE; v_customer jsonb;
BEGIN
  v_op:=toth_order_private.preorder_lease(p_operation_id,p_lease_token);
  IF v_op.reconciliation_state IN ('complete','blocked') THEN RETURN toth_order_private.preorder_item(v_op.id); END IF;
  IF v_op.delivery_state<>'received' OR v_op.commercial_state<>'approved' OR v_op.observation_source<>'authoritative_lookup'
    OR v_op.approved_total IS NULL OR v_op.external_id IS NULL THEN RAISE EXCEPTION 'toth_approval_not_confirmed' USING ERRCODE='55000'; END IF;
  SELECT * INTO v_deal FROM public.deals WHERE id=v_op.deal_id AND organization_id=v_op.organization_id FOR UPDATE;
  IF NOT FOUND OR v_deal.deleted_at IS NOT NULL OR v_deal.source_lead_id IS DISTINCT FROM v_op.lead_id
    OR v_deal.outcome NOT IN ('open','won') OR v_deal.currency IS DISTINCT FROM 'BRL' THEN
    RETURN toth_order_private.preorder_block(v_op.id,'toth_deal_changed');
  END IF;
  IF EXISTS(SELECT 1 FROM public.pipeline_entries p WHERE p.deal_id=v_deal.id AND p.organization_id IS DISTINCT FROM v_op.organization_id) THEN
    RETURN toth_order_private.preorder_block(v_op.id,'toth_pipeline_link_changed');
  END IF;
  v_customer:=toth_order_private.customer(v_op.organization_id,v_op.lead_id);
  IF v_customer IS NULL OR (v_customer->>'client_id')::uuid IS DISTINCT FROM v_op.client_id
    OR v_customer->>'customer_external_id' IS DISTINCT FROM v_op.request_snapshot->>'customer_external_id' THEN
    RETURN toth_order_private.preorder_block(v_op.id,'toth_client_link_changed');
  END IF;
  PERFORM toth_order_private.preorder_identity_lock(v_op.organization_id,v_op.external_id);
  IF EXISTS(SELECT 1 FROM public.upsell_orders WHERE organization_id=v_op.organization_id AND external_source='toth' AND external_id=v_op.external_id) THEN
    RETURN toth_order_private.preorder_block(v_op.id,'toth_existing_erp_order_conflict');
  END IF;
  SELECT count(*) INTO v_count FROM public.sale_events s WHERE s.organization_id=v_op.organization_id AND s.deal_id=v_deal.id
    AND s.event_type='sale' AND NOT EXISTS(SELECT 1 FROM public.sale_events r WHERE r.organization_id=s.organization_id AND r.reversed_event_id=s.id AND r.event_type='sale_reversed');
  IF (v_deal.outcome='won' AND (v_count<>1 OR v_deal.value IS DISTINCT FROM v_op.approved_total)) OR (v_deal.outcome='open' AND v_count<>0) THEN
    RETURN toth_order_private.preorder_block(v_op.id,'toth_existing_sale_conflict');
  END IF;
  IF v_deal.outcome='open' AND (v_deal.value IS DISTINCT FROM (v_op.request_snapshot->>'deal_value')::numeric
    OR v_op.request_snapshot->>'deal_outcome'<>'open') THEN RETURN toth_order_private.preorder_block(v_op.id,'toth_deal_changed'); END IF;
  BEGIN
    IF v_deal.outcome='open' THEN
      -- Canonical path, same transaction: the existing outcome trigger is the
      -- ONLY sale writer. No direct sale INSERT and no second ERP order here.
      UPDATE public.deals SET value=v_op.approved_total,outcome='won',outcome_source='api',outcome_at=clock_timestamp()
        WHERE id=v_deal.id AND organization_id=v_op.organization_id AND outcome='open';
    END IF;
    SELECT count(*) INTO v_count FROM public.sale_events s WHERE s.organization_id=v_op.organization_id AND s.deal_id=v_deal.id
      AND s.event_type='sale' AND NOT EXISTS(SELECT 1 FROM public.sale_events r WHERE r.organization_id=s.organization_id AND r.reversed_event_id=s.id AND r.event_type='sale_reversed');
    IF v_count<>1 THEN RAISE EXCEPTION 'toth_canonical_sale_missing'; END IF;
    SELECT s.* INTO v_sale FROM public.sale_events s WHERE s.organization_id=v_op.organization_id AND s.deal_id=v_deal.id
      AND s.event_type='sale' AND NOT EXISTS(SELECT 1 FROM public.sale_events r WHERE r.organization_id=s.organization_id AND r.reversed_event_id=s.id AND r.event_type='sale_reversed');
    IF v_sale.sale_value IS DISTINCT FROM v_op.approved_total OR v_sale.lead_id IS DISTINCT FROM v_op.lead_id
      OR v_sale.currency<>'BRL' OR v_sale.producer NOT IN ('funnel','deal') THEN RAISE EXCEPTION 'toth_canonical_sale_conflict'; END IF;
    UPDATE public.toth_preorder_operations SET reconciliation_state='complete',local_sale_event_id=v_sale.id,last_error_code=NULL,updated_at=clock_timestamp()
      WHERE id=v_op.id AND organization_id=v_op.organization_id;
    PERFORM toth_order_private.preorder_audit(v_op.id,'reconciled');
  EXCEPTION WHEN OTHERS THEN
    -- The subtransaction rolls back the deal and all canonical side effects.
    -- Keep the already-recorded ERP approval for a local-only retry.
    UPDATE public.toth_preorder_operations SET reconciliation_state='pending',last_error_code='toth_local_projection_failed',updated_at=clock_timestamp()
      WHERE id=v_op.id AND organization_id=v_op.organization_id;
    PERFORM toth_order_private.preorder_audit(v_op.id,'reconciliation_pending');
  END;
  RETURN toth_order_private.preorder_item(v_op.id);
END;
$$;
CREATE FUNCTION public.toth_release_preorder_operation(p_operation_id uuid,p_lease_token uuid) RETURNS void
LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$
  UPDATE public.toth_preorder_operations SET lease_token=NULL,lease_expires_at=NULL
    WHERE id=p_operation_id AND organization_id='4922638c-4909-494e-ba10-12282ec0b161'::uuid AND lease_token=p_lease_token;
$$;

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA toth_order_private FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.toth_preorder_can_read(uuid),public.toth_preorder_workspace(uuid),public.toth_request_order_send(uuid,integer),
 public.toth_preorder_legacy_import_guard(),public.toth_preorder_gain_guard(),public.toth_find_owned_preorder(uuid,text),public.toth_claim_preorder_operation(uuid),
 public.toth_mark_preorder_sending(uuid,uuid),public.toth_record_preorder_observation(uuid,uuid,jsonb),
 public.toth_mark_preorder_uncertain(uuid,uuid,text),public.toth_block_preorder_operation(uuid,uuid,text),
 public.toth_reconcile_preorder_operation(uuid,uuid),public.toth_release_preorder_operation(uuid,uuid) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.toth_preorder_can_read(uuid),public.toth_preorder_workspace(uuid),public.toth_request_order_send(uuid,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.toth_find_owned_preorder(uuid,text),public.toth_claim_preorder_operation(uuid),
 public.toth_mark_preorder_sending(uuid,uuid),public.toth_record_preorder_observation(uuid,uuid,jsonb),
 public.toth_mark_preorder_uncertain(uuid,uuid,text),public.toth_block_preorder_operation(uuid,uuid,text),
 public.toth_reconcile_preorder_operation(uuid,uuid),public.toth_release_preorder_operation(uuid,uuid) TO service_role;
COMMIT;
