-- Dedicated ingress canary: receipts only. No cron, no routing/config change.
-- Service-only technical inbox; tenant identity is resolved before enqueue and
-- checked again here. Payload may contain provider tokens: never expose to UI.
CREATE TABLE public.whatsapp_ingress_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  enqueue_sequence bigint GENERATED ALWAYS AS IDENTITY UNIQUE,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  instance_id uuid NOT NULL REFERENCES public.whatsapp_instances(id) ON DELETE CASCADE,
  event_key text NOT NULL,
  event_name text NOT NULL CHECK (event_name = 'messages_update'),
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object' AND octet_length(payload::text) <= 2097152),
  payload_bytes integer GENERATED ALWAYS AS (octet_length(payload::text)) STORED,
  path_instance_id text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','completed','dead_letter')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 8),
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  lease_until timestamptz,
  lease_token uuid,
  last_error_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);
ALTER TABLE public.whatsapp_ingress_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.whatsapp_ingress_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.whatsapp_ingress_events FROM service_role;
GRANT SELECT ON TABLE public.whatsapp_ingress_events TO service_role;
CREATE INDEX whatsapp_ingress_events_due ON public.whatsapp_ingress_events(instance_id,next_attempt_at,created_at) WHERE status='pending';
CREATE INDEX whatsapp_ingress_events_leases ON public.whatsapp_ingress_events(instance_id,lease_until) WHERE status='processing';
CREATE INDEX whatsapp_ingress_events_retention ON public.whatsapp_ingress_events(completed_at) WHERE status='completed';
CREATE INDEX whatsapp_ingress_events_org ON public.whatsapp_ingress_events(organization_id);
CREATE INDEX whatsapp_ingress_events_fifo ON public.whatsapp_ingress_events(instance_id,enqueue_sequence) WHERE status IN ('pending','processing');

CREATE TABLE public.whatsapp_ingress_budget (
  singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),
  row_count bigint NOT NULL DEFAULT 0 CHECK(row_count>=0),
  payload_bytes bigint NOT NULL DEFAULT 0 CHECK(payload_bytes>=0)
);
INSERT INTO public.whatsapp_ingress_budget(singleton) VALUES(true);
ALTER TABLE public.whatsapp_ingress_budget ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.whatsapp_ingress_budget FROM PUBLIC,anon,authenticated;
REVOKE ALL ON TABLE public.whatsapp_ingress_budget FROM service_role;
GRANT SELECT ON TABLE public.whatsapp_ingress_budget TO service_role;

CREATE FUNCTION public.account_whatsapp_ingress_budget()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO public AS $$
BEGIN
  -- Atomic counter replaces count/sum scans on every admission. AFTER triggers
  -- see the stored generated byte count, including multi-row deletes/rollbacks.
  IF TG_OP='INSERT' THEN
    UPDATE public.whatsapp_ingress_budget SET row_count=row_count+1,payload_bytes=payload_bytes+NEW.payload_bytes
      WHERE singleton AND row_count<20000 AND payload_bytes+NEW.payload_bytes<=67108864;
  ELSIF TG_OP='DELETE' THEN
    UPDATE public.whatsapp_ingress_budget SET row_count=row_count-1,payload_bytes=payload_bytes-OLD.payload_bytes WHERE singleton;
  ELSE
    UPDATE public.whatsapp_ingress_budget SET payload_bytes=payload_bytes+NEW.payload_bytes-OLD.payload_bytes
      WHERE singleton AND payload_bytes+NEW.payload_bytes-OLD.payload_bytes<=67108864;
  END IF;
  IF NOT FOUND THEN RAISE EXCEPTION 'ingress capacity exhausted' USING ERRCODE='54000'; END IF;
  RETURN NULL;
END $$;
CREATE TRIGGER account_whatsapp_ingress_budget AFTER INSERT OR DELETE OR UPDATE OF payload
  ON public.whatsapp_ingress_events FOR EACH ROW EXECUTE FUNCTION public.account_whatsapp_ingress_budget();
REVOKE ALL ON FUNCTION public.account_whatsapp_ingress_budget() FROM PUBLIC,anon,authenticated;

CREATE FUNCTION public.enqueue_whatsapp_ingress_event(p_organization_id uuid,p_instance_id uuid,p_event_name text,p_payload jsonb,p_path_instance_id text DEFAULT NULL)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO public AS $$
DECLARE v_id uuid; v_key text;
BEGIN
  IF p_event_name IS DISTINCT FROM 'messages_update' OR jsonb_typeof(p_payload) IS DISTINCT FROM 'object'
    OR octet_length(p_payload::text)>2097152 OR length(coalesce(p_path_instance_id,''))>200 THEN
    RAISE EXCEPTION 'invalid ingress event' USING ERRCODE='22023';
  END IF;
  IF NOT EXISTS(SELECT 1 FROM public.whatsapp_instances WHERE id=p_instance_id AND organization_id=p_organization_id) THEN
    RAISE EXCEPTION 'instance organization mismatch' USING ERRCODE='42501';
  END IF;
  -- Fingerprint only, deliberately NOT UNIQUE. The same pin payload can be a
  -- legitimate later pin after an unpin; message ID is not a unique event ID.
  v_key := encode(sha256(convert_to(jsonb_build_array(p_event_name,p_path_instance_id,p_payload)::text,'UTF8')),'hex');
  INSERT INTO public.whatsapp_ingress_events(organization_id,instance_id,event_key,event_name,payload,path_instance_id)
    VALUES(p_organization_id,p_instance_id,v_key,p_event_name,p_payload,p_path_instance_id)
    RETURNING id INTO v_id;
  RETURN v_id;
END $$;

CREATE FUNCTION public.claim_whatsapp_ingress_events(p_instance_ids uuid[],p_batch_size integer DEFAULT 10)
RETURNS SETOF public.whatsapp_ingress_events LANGUAGE plpgsql SECURITY DEFINER SET search_path TO public AS $$
DECLARE v_instance uuid; v_event public.whatsapp_ingress_events%ROWTYPE; v_count integer := 0;
BEGIN
  IF coalesce(cardinality(p_instance_ids),0)=0 OR p_batch_size IS NULL OR p_batch_size<1 OR p_batch_size>20 THEN
    RAISE EXCEPTION 'invalid ingress claim scope' USING ERRCODE='22023';
  END IF;
  -- A worker lost on its final attempt must become visible dead-letter work.
  UPDATE public.whatsapp_ingress_events SET status='dead_letter',lease_until=NULL,lease_token=NULL,
    last_error_code='lease_exhausted',updated_at=now()
    WHERE instance_id=ANY(p_instance_ids) AND status='processing' AND lease_until<now() AND attempts>=8;
  FOREACH v_instance IN ARRAY p_instance_ids LOOP
    -- Lock the instance before the subsequent statement gets its fresh
    -- snapshot. Row SKIP LOCKED alone would allow simultaneous distinct events
    -- from the same instance, reordering pin/unpin/reaction transitions.
    IF NOT pg_try_advisory_xact_lock(hashtextextended(v_instance::text,29)) THEN CONTINUE; END IF;
    SELECT * INTO v_event FROM public.whatsapp_ingress_events
      WHERE instance_id=v_instance AND status IN ('pending','processing')
      ORDER BY enqueue_sequence LIMIT 1 FOR UPDATE;
    IF NOT FOUND OR v_event.attempts>=8 THEN CONTINUE; END IF;
    IF (v_event.status='pending' AND v_event.next_attempt_at>now())
      OR (v_event.status='processing' AND v_event.lease_until>=now()) THEN CONTINUE; END IF;
    RETURN QUERY UPDATE public.whatsapp_ingress_events e SET status='processing',attempts=e.attempts+1,
      lease_token=gen_random_uuid(),lease_until=now()+interval '2 minutes',updated_at=now()
      WHERE e.id=v_event.id RETURNING e.*;
    v_count:=v_count+1;
    EXIT WHEN v_count>=p_batch_size;
  END LOOP;
END $$;

CREATE FUNCTION public.finish_whatsapp_ingress_event(p_id uuid,p_lease_token uuid,p_error_code text DEFAULT NULL)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO public AS $$
DECLARE v_count integer;
BEGIN
  IF p_error_code IS NOT NULL AND p_error_code !~ '^[a-z0-9_]{1,80}$' THEN
    RAISE EXCEPTION 'invalid ingress error code' USING ERRCODE='22023';
  END IF;
  UPDATE public.whatsapp_ingress_events SET
    status=CASE WHEN p_error_code IS NULL THEN 'completed' WHEN attempts>=8 THEN 'dead_letter' ELSE 'pending' END,
    next_attempt_at=CASE WHEN p_error_code IS NULL THEN next_attempt_at ELSE now()+make_interval(secs=>least(1800,power(2,attempts)::integer*5)) END,
    completed_at=CASE WHEN p_error_code IS NULL THEN now() ELSE NULL END,
    lease_until=NULL,lease_token=NULL,last_error_code=p_error_code,updated_at=now()
    WHERE id=p_id AND lease_token=p_lease_token AND status='processing';
  GET DIAGNOSTICS v_count=ROW_COUNT;
  RETURN v_count=1;
END $$;

CREATE FUNCTION public.cleanup_whatsapp_ingress_events(p_instance_ids uuid[],p_limit integer DEFAULT 500)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path TO public AS $$
DECLARE v_count integer;
BEGIN
  IF coalesce(cardinality(p_instance_ids),0)=0 OR p_limit IS NULL OR p_limit<1 OR p_limit>1000 THEN
    RAISE EXCEPTION 'invalid ingress cleanup scope' USING ERRCODE='22023';
  END IF;
  -- Preserve pending and dead-letter evidence; only confirmed completed work.
  DELETE FROM public.whatsapp_ingress_events WHERE id IN (
    SELECT id FROM public.whatsapp_ingress_events WHERE instance_id=ANY(p_instance_ids)
      AND status='completed' AND completed_at<now()-interval '2 days'
    ORDER BY completed_at LIMIT p_limit FOR UPDATE SKIP LOCKED
  );
  GET DIAGNOSTICS v_count=ROW_COUNT;
  RETURN v_count;
END $$;

REVOKE ALL ON FUNCTION public.enqueue_whatsapp_ingress_event(uuid,uuid,text,jsonb,text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.claim_whatsapp_ingress_events(uuid[],integer) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.finish_whatsapp_ingress_event(uuid,uuid,text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.cleanup_whatsapp_ingress_events(uuid[],integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_whatsapp_ingress_event(uuid,uuid,text,jsonb,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_whatsapp_ingress_events(uuid[],integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.finish_whatsapp_ingress_event(uuid,uuid,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_whatsapp_ingress_events(uuid[],integer) TO service_role;
