// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createTracedFetch } from '@/core/trace/request-trace';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL || 'https://placeholders.supabase.co', SUPABASE_PUBLISHABLE_KEY || 'placeholder', {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Carimba x-torque-session-id / x-torque-request-id em toda saída (PostgREST,
  // RPC, Storage, functions.invoke). Ver src/core/trace/request-trace.ts.
  global: {
    fetch: createTracedFetch(),
  },
});